import SwiftUI

// GENERATED by scripts/native/make-theme.mjs from src/app/globals.css and src/lib/motion.ts. Do not
// edit: re-run the script instead.
//
// Two documents own that file, and the reconciliation between them is the
// judgement call it documents: Uber owns the chrome (the ink/canvas duet, the
// grayscale ramp, the pill, the type ladder), Duolingo owns the state (the
// tactile lip under every button, the uppercase tracked label, and colour used
// only where the game needs it — streak, correct, gold). Green is the one
// control that is not navigation: the button you press inside a study session.

/// The palette, in both polarities — the same system flipped, resolved live so a
/// device changing appearance mid-session repaints rather than restarting.
public struct RevisioColors: Sendable {
    public let background: Color
    public let foreground: Color
    public let card: Color
    public let cardForeground: Color
    public let popover: Color
    public let primary: Color
    public let primaryForeground: Color
    public let secondary: Color
    public let secondaryForeground: Color
    public let muted: Color
    public let mutedForeground: Color
    public let accent: Color
    public let accentForeground: Color
    public let destructive: Color
    public let destructiveForeground: Color
    public let border: Color
    public let borderStrong: Color
    public let input: Color
    public let ring: Color
    public let good: Color
    public let goodPressed: Color
    public let goodSoft: Color
    public let streak: Color
    public let gold: Color
    public let info: Color
    public let band: Color
    public let bandForeground: Color
    public let bandCard: Color
    public let bandBorder: Color
    public let bandMuted: Color
    public let bandSecondary: Color
    public let lip: Color
    public let lipSoft: Color
    public let scrim: Color

    public static let light = RevisioColors(
        background: Color(hex: 0xFFFFFFFF),
        foreground: Color(hex: 0x000000FF),
        card: Color(hex: 0xFFFFFFFF),
        cardForeground: Color(hex: 0x000000FF),
        popover: Color(hex: 0xFFFFFFFF),
        primary: Color(hex: 0x000000FF),
        primaryForeground: Color(hex: 0xFFFFFFFF),
        secondary: Color(hex: 0xEFEFEFFF),
        secondaryForeground: Color(hex: 0x000000FF),
        muted: Color(hex: 0xF3F3F3FF),
        mutedForeground: Color(hex: 0x5E5E5EFF),
        accent: Color(hex: 0xEFEFEFFF),
        accentForeground: Color(hex: 0x000000FF),
        destructive: Color(hex: 0xFF4B4BFF),
        destructiveForeground: Color(hex: 0xFFFFFFFF),
        border: Color(hex: 0xE2E2E2FF),
        borderStrong: Color(hex: 0xD0D0D0FF),
        input: Color(hex: 0xEFEFEFFF),
        ring: Color(hex: 0x000000FF),
        good: Color(hex: 0x58CC02FF),
        goodPressed: Color(hex: 0x58A700FF),
        goodSoft: Color(hex: 0xD7FFB8FF),
        streak: Color(hex: 0xFF9600FF),
        gold: Color(hex: 0xFFC800FF),
        info: Color(hex: 0x1CB0F6FF),
        band: Color(hex: 0x000000FF),
        bandForeground: Color(hex: 0xFFFFFFFF),
        bandCard: Color(hex: 0x1A1A1AFF),
        bandBorder: Color(hex: 0x333333FF),
        bandMuted: Color(hex: 0xAFAFAFFF),
        bandSecondary: Color(hex: 0x242424FF),
        lip: Color(hex: 0x00000047),
        lipSoft: Color(hex: 0xDCDCDCFF),
        scrim: Color(hex: 0x00000066)
    )

    public static let dark = RevisioColors(
        background: Color(hex: 0x000000FF),
        foreground: Color(hex: 0xFFFFFFFF),
        card: Color(hex: 0x141414FF),
        cardForeground: Color(hex: 0xFFFFFFFF),
        popover: Color(hex: 0x1A1A1AFF),
        primary: Color(hex: 0xFFFFFFFF),
        primaryForeground: Color(hex: 0x000000FF),
        secondary: Color(hex: 0x282828FF),
        secondaryForeground: Color(hex: 0xFFFFFFFF),
        muted: Color(hex: 0x1C1C1CFF),
        mutedForeground: Color(hex: 0xAFAFAFFF),
        accent: Color(hex: 0x282828FF),
        accentForeground: Color(hex: 0xFFFFFFFF),
        destructive: Color(hex: 0xFF6B6BFF),
        destructiveForeground: Color(hex: 0x000000FF),
        border: Color(hex: 0x2E2E2EFF),
        borderStrong: Color(hex: 0x4B4B4BFF),
        input: Color(hex: 0x282828FF),
        ring: Color(hex: 0xFFFFFFFF),
        good: Color(hex: 0x58CC02FF),
        goodPressed: Color(hex: 0x3F9400FF),
        goodSoft: Color(hex: 0x1F3608FF),
        streak: Color(hex: 0xFFA53DFF),
        gold: Color(hex: 0xFFD23FFF),
        info: Color(hex: 0x1CB0F6FF),
        band: Color(hex: 0x141414FF),
        bandForeground: Color(hex: 0xFFFFFFFF),
        bandCard: Color(hex: 0x1F1F1FFF),
        bandBorder: Color(hex: 0x2E2E2EFF),
        bandMuted: Color(hex: 0x9A9A9AFF),
        bandSecondary: Color(hex: 0x262626FF),
        lip: Color(hex: 0xC9C9C9FF),
        lipSoft: Color(hex: 0x1F1F1FFF),
        scrim: Color(hex: 0x000000A8)
    )

    public static func forScheme(_ scheme: ColorScheme) -> RevisioColors {
        scheme == .dark ? .dark : .light
    }
}

public extension Color {
    /// 0xRRGGBBAA, the same encoding the Kotlin side uses.
    init(hex: UInt64) {
        let red = Double((hex >> 24) & 0xFF) / 255
        let green = Double((hex >> 16) & 0xFF) / 255
        let blue = Double((hex >> 8) & 0xFF) / 255
        let alpha = Double(hex & 0xFF) / 255
        self.init(.sRGB, red: red, green: green, blue: blue, opacity: alpha)
    }
}

/// The radius ladder, and the pill that is the only interactive shape.
public enum Radius {
    public static let xs: CGFloat = 6
    public static let sm: CGFloat = 8
    public static let md: CGFloat = 12
    public static let lg: CGFloat = 16
    public static let xl: CGFloat = 20
    public static let xxl: CGFloat = 24
    public static let pill: CGFloat = 999
    public static let base: CGFloat = 16
}

/// The three documented drops. Cards stay flat: elevation is a colour change.
public struct ShadowSpec: Sendable {
    public let x: CGFloat
    public let y: CGFloat
    public let blur: CGFloat
    public let spread: CGFloat
    public let alpha: Double
}

public enum Shadows {

}

/// The two curves the whole app animates on.
public enum Easing {
    public static let snap = Animation.timingCurve(0.16, 1, 0.3, 1)
    public static let out = Animation.timingCurve(0.22, 1, 0.36, 1)
}

///
/// The motion language — `src/lib/motion.ts`, the single owner of every
/// duration, curve, spring and gesture in the product.
///
/// `globals.css` carries two curves; the springs live here, and the ports
/// animated on a hand-picked 90ms tween until they were read from this file.
/// SwiftUI's `interpolatingSpring(mass:stiffness:damping:)` is the web's spring
/// equation written out, so these are the numbers and not a translation of them.
///
public enum Motion {
    /// Seconds, as the web authors them.
    public enum Durations {
        public static let instant: Double = 0.12
        public static let quick: Double = 0.18
        public static let base: Double = 0.3
        public static let slow: Double = 0.46
        public static let reveal: Double = 0.6
    }

    /// A curve at whatever duration you are about to run it for.
    public enum Curves {
        public static func out(_ duration: Double) -> Animation {
            .timingCurve(0.22, 1, 0.36, 1, duration: duration)
        }
        public static func outSoft(_ duration: Double) -> Animation {
            .timingCurve(0.21, 0.47, 0.32, 0.98, duration: duration)
        }
        public static func inOut(_ duration: Double) -> Animation {
            .timingCurve(0.65, 0, 0.35, 1, duration: duration)
        }
        public static func easeIn(_ duration: Double) -> Animation {
            .timingCurve(0.4, 0, 1, 1, duration: duration)
        }
    }

    /// The pairs the web actually runs, ready to hand to `withAnimation`.
    public enum Enter {
        public static let base = Curves.out(Durations.base)
        public static let reveal = Curves.out(Durations.reveal)
    }

    public enum Exit {
        public static let quick = Curves.easeIn(Durations.quick)
        public static let instant = Curves.easeIn(Durations.instant)
    }

    /// A spring as the web states it. `.animation` is the same spring in SwiftUI.
    public struct SpringSpec: Sendable {
        public let mass: Double
        public let stiffness: Double
        public let damping: Double

        public var animation: Animation {
            .interpolatingSpring(mass: mass, stiffness: stiffness, damping: damping)
        }
    }

    /// By intent: `settle` is the workhorse, `press` has teeth, `pop` bounces.
    public enum Springs {
    /// stiffness 640 · damping 30 · mass 0.5
    public static let press = SpringSpec(mass: 0.5, stiffness: 640, damping: 30)
    /// stiffness 480 · damping 38 · mass 0.75
    public static let layout = SpringSpec(mass: 0.75, stiffness: 480, damping: 38)
    /// stiffness 300 · damping 28 · mass 0.85
    public static let settle = SpringSpec(mass: 0.85, stiffness: 300, damping: 28)
    /// stiffness 150 · damping 26 · mass 1
    public static let meter = SpringSpec(mass: 1, stiffness: 150, damping: 26)
    /// stiffness 260 · damping 30 · mass 0.9
    public static let soft = SpringSpec(mass: 0.9, stiffness: 260, damping: 30)
    /// stiffness 420 · damping 22 · mass 0.7
    public static let pop = SpringSpec(mass: 0.7, stiffness: 420, damping: 22)
    }

    /// Press: the spec's `scale(0.95)`, which every tappable surface uses.
    public static let pressScale: CGFloat = 0.95
    public static let hoverScale: CGFloat = 1.015

    /// Entrances: rise and settle. Cards arrive at a hair under full size.
    public static let enterRise: CGFloat = 12
    public static let enterScale: CGFloat = 0.96
    public static let enterScaleRise: CGFloat = 8
    public static let routeRise: CGFloat = 10

    /// A rail that slides in from the side.
    public static let railSlide: CGFloat = 32

    /// A sheet starts this far below the screen, as a fraction of its height.
    public static let sheetTravel: CGFloat = 1.02

    /// Stagger, and the cap that keeps a long list from trickling in.
    public static let staggerStep: Double = 0.05
    public static let staggerChildren: Double = 0.04
    public static let listStep: Double = 0.035
    public static let listCap: Double = 0.32

    /// How far above the fold a scroll reveal fires, once.
    public static let revealMargin: CGFloat = 80

    /// The delay before one child of a staggered list arrives, capped as above.
    public static func stagger(_ index: Int) -> Double {
        min(Double(index) * listStep, listCap)
    }
}

/** The type ladder, as the phone step of a responsive scale. */
public struct TypeToken: Sendable {
    public let size: CGFloat
    public let weight: Font.Weight
    public let lineHeight: CGFloat
    public let tracking: CGFloat
    public let uppercase: Bool

    public var font: Font {
        .system(size: size, weight: weight)
    }

    /// Tracking is authored in em; SwiftUI wants points.
    public var trackingPoints: CGFloat { tracking * size }

    /// The label treatment: uppercased and letterspaced. Never applied to prose.
    public func text(_ string: String) -> String {
        uppercase ? string.uppercased() : string
    }
}

public enum Type {
    /// `t-hero`
    public static let hero = TypeToken(size: 32, weight: .bold, lineHeight: 1.08, tracking: 0, uppercase: false)
    /// `t-display`
    public static let display = TypeToken(size: 28, weight: .bold, lineHeight: 1.15, tracking: 0, uppercase: false)
    /// `t-display-md`
    public static let displayMd = TypeToken(size: 24, weight: .bold, lineHeight: 1.25, tracking: 0, uppercase: false)
    /// `t-display-sm`
    public static let displaySm = TypeToken(size: 20, weight: .bold, lineHeight: 1.3, tracking: 0, uppercase: false)
    /// `t-title`
    public static let title = TypeToken(size: 22, weight: .bold, lineHeight: 1.25, tracking: 0, uppercase: false)
    /// `t-lead`
    public static let lead = TypeToken(size: 18, weight: .medium, lineHeight: 1.4, tracking: 0, uppercase: false)
    /// `t-lead-airy`
    public static let leadAiry = TypeToken(size: 17, weight: .regular, lineHeight: 1.45, tracking: 0, uppercase: false)
    /// `t-tagline`
    public static let tagline = TypeToken(size: 19, weight: .bold, lineHeight: 1.35, tracking: 0, uppercase: false)
    /// `t-strong`
    public static let strong = TypeToken(size: 16, weight: .medium, lineHeight: 1.3, tracking: 0, uppercase: false)
    /// `t-body`
    public static let body = TypeToken(size: 16, weight: .regular, lineHeight: 1.5, tracking: 0, uppercase: false)
    /// `t-caption`
    public static let caption = TypeToken(size: 14, weight: .regular, lineHeight: 1.43, tracking: 0, uppercase: false)
    /// `t-caption-s`
    public static let captionS = TypeToken(size: 14, weight: .medium, lineHeight: 1.3, tracking: 0, uppercase: false)
    /// `t-fine`
    public static let fine = TypeToken(size: 12, weight: .regular, lineHeight: 1.35, tracking: 0, uppercase: false)
    /// `t-micro`
    public static let micro = TypeToken(size: 10, weight: .medium, lineHeight: 1.3, tracking: 0, uppercase: false)
    /// `t-label`
    public static let label = TypeToken(size: 14, weight: .bold, lineHeight: 1.2, tracking: 0.08, uppercase: true)
    /// `t-eyebrow`
    public static let eyebrow = TypeToken(size: 12, weight: .bold, lineHeight: 1.3, tracking: 0.1, uppercase: true)
    /// `t-num`
    public static let num = TypeToken(size: 30, weight: .bold, lineHeight: 1.1, tracking: 0, uppercase: false)
    /// `t-num-sm`
    public static let numSm = TypeToken(size: 24, weight: .bold, lineHeight: 1.15, tracking: 0, uppercase: false)
}

/** Geometry the controls are built from, so a tap target is never improvised. */
public enum Metrics {
    public static let buttonMinHeight: CGFloat = 44
    public static let buttonPadding: CGFloat = 20
    public static let optionMinHeight: CGFloat = 56
    public static let inputMinHeight: CGFloat = 48
    public static let inputBorder: CGFloat = 2
    public static let meterHeight: CGFloat = 10
    public static let chipMinHeight: CGFloat = 30
    public static let pillOffset: CGFloat = 3
    public static let goodLipOffset: CGFloat = 4
    public static let iconMinHeight: CGFloat = 40
    public static let navHeight: CGFloat = 64
}
