package app.revisio.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

// GENERATED by scripts/native/make-icons.mjs from src/components/ui/icons.tsx
// and lucide-react 1.47.0. Do not edit: re-run the script.
//
// These are the website's icons, not lookalikes. Each entry is the same
// geometry the browser draws, stroked at the registry's 1.75 weight on the same
// 24px grid, and drawn in the colour it is asked for rather than a fixed one —
// which is what lets an inactive nav item read muted and an active one read ink.

private fun icon(name: String, weight: Float, vararg paths: String): ImageVector {
    val builder = ImageVector.Builder(
        name = name,
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    )
    paths.forEach { d ->
        builder.addPath(
            pathData = PathParser().parsePathString(d).toNodes(),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = weight,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        )
    }
    return builder.build()
}

private fun buildIcons(): List<Pair<String, List<String>>> = listOf(
    "dashboard" to listOf(
        "M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8",
        "M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z",
    ),
    "review" to listOf(
        "m2 9 3-3 3 3",
        "M13 18H7a2 2 0 0 1-2-2V6",
        "m22 15-3 3-3-3",
        "M11 6h6a2 2 0 0 1 2 2v10",
    ),
    "learn" to listOf(
        "M12 5v16",
        "M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z",
    ),
    "cram" to listOf(
        "M 10 2 L 14 2",
        "M 12 14 L 15 11",
        "M 4 14 a 8 8 0 1 0 16 0 a 8 8 0 1 0 -16 0 Z",
    ),
    "exam" to listOf(
        "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z",
        "M14 2v5a1 1 0 0 0 1 1h5",
        "M10 9H8",
        "M16 13H8",
        "M16 17H8",
    ),
    "progress" to listOf(
        "M3 3v16a2 2 0 0 0 2 2h16",
        "m19 9-5 5-4-4-3 3",
    ),
    "library" to listOf(
        "M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z",
        "M12 22V12",
        "M 3.29 7 L 12 12 L 20.71 7",
        "m7.5 4.27 9 5.15",
    ),
    "teacher" to listOf(
        "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2",
        "M16 3.128a4 4 0 0 1 0 7.744",
        "M22 21v-2a4 4 0 0 0-3-3.87",
        "M 5 7 a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0 Z",
    ),
    "admin" to listOf(
        "M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z",
    ),
    "due" to listOf(
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0 Z",
        "M 12 8 L 12 12",
        "M 12 16 L 12.01 16",
    ),
    "reviewed" to listOf(
        "M21.801 10A10 10 0 1 1 17 3.335",
        "m9 11 3 3L22 4",
    ),
    "correct" to listOf(
        "M20 6 9 17l-5-5",
    ),
    "streak" to listOf(
        "M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0 5 5 0 0 1 1-3 1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4",
    ),
    "level" to listOf(
        "M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z",
    ),
    "xp" to listOf(
        "M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z",
        "M20 2v4",
        "M22 4h-4",
        "M 2 20 a 2 2 0 1 0 4 0 a 2 2 0 1 0 -4 0 Z",
    ),
    "league" to listOf(
        "M10 14.66V17a1 1 0 0 1-1 1 2 2 0 0 0-2 2v2",
        "M14 14.66V17a1 1 0 0 0 1 1 2 2 0 0 1 2 2v2",
        "M17.916 10H19.5A2.5 2.5 0 0 0 22 7.5V5a1 1 0 0 0-1-1h-3",
        "M4 22h16",
        "M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z",
        "M6.084 10H4.5A2.5 2.5 0 0 1 2 7.5V5a1 1 0 0 1 1-1h3",
    ),
    "rank" to listOf(
        "M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15",
        "M11 12 5.12 2.2",
        "m13 12 5.88-9.8",
        "M8 7h8",
        "M 7 17 a 5 5 0 1 0 10 0 a 5 5 0 1 0 -10 0 Z",
        "M12 18v-2h-.5",
    ),
    "crown" to listOf(
        "M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z",
        "M5 21h14",
    ),
    "clash" to listOf(
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0 Z",
        "M 22 12 L 18 12",
        "M 6 12 L 2 12",
        "M 12 6 L 12 2",
        "M 12 22 L 12 18",
    ),
    "form" to listOf(
        "M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2",
    ),
    "gauge" to listOf(
        "m12 14 4-4",
        "M3.34 19a10 10 0 1 1 17.32 0",
    ),
    "zoneUp" to listOf(
        "m17 11-5-5-5 5",
        "m17 18-5-5-5 5",
    ),
    "zoneDown" to listOf(
        "m7 6 5 5 5-5",
        "m7 13 5 5 5-5",
    ),
    "climb" to listOf(
        "M7 7h10v10",
        "M7 17 17 7",
    ),
    "next" to listOf(
        "M5 12h14",
        "m12 5 7 7-7 7",
    ),
    "expand" to listOf(
        "m9 18 6-6-6-6",
    ),
    "collapse" to listOf(
        "m6 9 6 6 6-6",
    ),
    "search" to listOf(
        "m21 21-4.34-4.34",
        "M 3 11 a 8 8 0 1 0 16 0 a 8 8 0 1 0 -16 0 Z",
    ),
    "download" to listOf(
        "M12 15V3",
        "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4",
        "m7 10 5 5 5-5",
    ),
    "upload" to listOf(
        "M12 3v12",
        "m17 8-5-5-5 5",
        "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4",
    ),
    "rotate" to listOf(
        "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8",
        "M21 3v5h-5",
        "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16",
        "M8 16H3v5",
    ),
    "add" to listOf(
        "M5 12h14",
        "M12 5v14",
    ),
    "rocket" to listOf(
        "M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5",
        "M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09",
        "M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z",
        "M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05",
    ),
    "edit" to listOf(
        "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z",
        "m15 5 4 4",
    ),
    "remove" to listOf(
        "M10 11v6",
        "M14 11v6",
        "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6",
        "M3 6h18",
        "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2",
    ),
    "close" to listOf(
        "M18 6 6 18",
        "m6 6 12 12",
    ),
    "signOut" to listOf(
        "m16 17 5-5-5-5",
        "M21 12H9",
        "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4",
    ),
    "sun" to listOf(
        "M 8 12 a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0 Z",
        "M12 2v2",
        "M12 20v2",
        "m4.93 4.93 1.41 1.41",
        "m17.66 17.66 1.41 1.41",
        "M2 12h2",
        "M20 12h2",
        "m6.34 17.66-1.41 1.41",
        "m19.07 4.93-1.41 1.41",
    ),
    "moon" to listOf(
        "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401",
    ),
    "more" to listOf(
        "M 11 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0 Z",
        "M 18 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0 Z",
        "M 4 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0 Z",
    ),
    "clock" to listOf(
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0 Z",
        "M12 6v6l4 2",
    ),
    "week" to listOf(
        "M16 14v2.2l1.6 1",
        "M16 2v3",
        "M21 7.338V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h2.338",
        "M3 9h5.859",
        "M8 2v3",
        "M 10 16 a 6 6 0 1 0 12 0 a 6 6 0 1 0 -12 0 Z",
    ),
    "resume" to listOf(
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0 Z",
        "m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z",
    ),
    "swords" to listOf(
        "M16 7h6v6",
        "m22 7-8.5 8.5-5-5L2 17",
    ),
    "topic" to listOf(
        "M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z",
        "M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12",
        "M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17",
    ),
    "notes" to listOf(
        "M13 5h8",
        "M13 12h8",
        "M13 19h8",
        "m3 17 2 2 4-4",
        "m3 7 2 2 4-4",
    ),
    "spec" to listOf(
        "M 9 2 L 15 2 a 1 1 0 0 1 1 1 L 16 5 a 1 1 0 0 1 -1 1 L 9 6 a 1 1 0 0 1 -1 -1 L 8 3 a 1 1 0 0 1 1 -1 Z",
        "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2",
        "M12 11h4",
        "M12 16h4",
        "M8 11h.01",
        "M8 16h.01",
    ),
    "class" to listOf(
        "M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z",
        "M22 10v6",
        "M6 12.5V16a6 3 0 0 0 12 0v-3.5",
    ),
    "join" to listOf(
        "M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z",
        "m16 9-5.5 5.5L8 12",
    ),
    "publish" to listOf(
        "M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5",
        "M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09",
        "M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z",
        "M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05",
    ),
    "unpublish" to listOf(
        "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49",
        "M14.084 14.158a3 3 0 0 1-4.242-4.242",
        "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143",
        "m2 2 20 20",
    ),
    "visible" to listOf(
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0 Z",
        "M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20",
        "M2 12h20",
    ),
    "merge" to listOf(
        "M 15 18 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0 Z",
        "M 3 6 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0 Z",
        "M6 21V9a9 9 0 0 0 9 9",
    ),
    "structure" to listOf(
        "M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z",
        "M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12",
        "M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17",
    ),
    "private" to listOf(
        "M 5 11 L 19 11 a 2 2 0 0 1 2 2 L 21 20 a 2 2 0 0 1 -2 2 L 5 22 a 2 2 0 0 1 -2 -2 L 3 13 a 2 2 0 0 1 2 -2 Z",
        "M7 11V7a5 5 0 0 1 10 0v4",
    ),
    "person" to listOf(
        "M 7 8 a 5 5 0 1 0 10 0 a 5 5 0 1 0 -10 0 Z",
        "M20 21a8 8 0 0 0-16 0",
    ),
    "mail" to listOf(
        "m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7",
        "M 4 4 L 20 4 a 2 2 0 0 1 2 2 L 22 18 a 2 2 0 0 1 -2 2 L 4 20 a 2 2 0 0 1 -2 -2 L 2 6 a 2 2 0 0 1 2 -2 Z",
    ),
    "secure" to listOf(
        "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z",
        "m9 12 2 2 4-4",
    ),
    "achievements" to listOf(
        "m15.477 12.89 1.515 8.526a.5.5 0 0 1-.81.47l-3.58-2.687a1 1 0 0 0-1.197 0l-3.586 2.686a.5.5 0 0 1-.81-.469l1.514-8.526",
        "M 6 8 a 6 6 0 1 0 12 0 a 6 6 0 1 0 -12 0 Z",
    ),
    "start" to listOf(
        "M4 16v-2.38C4 11.5 2.97 10.5 3 8c.03-2.72 1.49-6 4.5-6C9.37 2 10 3.8 10 5.5c0 3.11-2 5.66-2 8.68V16a2 2 0 1 1-4 0Z",
        "M20 20v-2.38c0-2.12 1.03-3.12 1-5.62-.03-2.72-1.49-6-4.5-6C14.63 6 14 7.8 14 9.5c0 3.11 2 5.66 2 8.68V20a2 2 0 1 0 4 0Z",
        "M16 17h4",
        "M4 13h4",
    ),
    "schedule" to listOf(
        "M8 2v3",
        "M16 2v3",
        "M 5 3 L 19 3 a 2 2 0 0 1 2 2 L 21 19 a 2 2 0 0 1 -2 2 L 5 21 a 2 2 0 0 1 -2 -2 L 3 5 a 2 2 0 0 1 2 -2 Z",
        "M3 9h18",
        "M8 13h.01",
        "M12 13h.01",
        "M16 13h.01",
        "M8 17h.01",
        "M12 17h.01",
        "M16 17h.01",
    ),
    "checked" to listOf(
        "M8 2v3",
        "M16 2v3",
        "M 5 3 L 19 3 a 2 2 0 0 1 2 2 L 21 19 a 2 2 0 0 1 -2 2 L 5 21 a 2 2 0 0 1 -2 -2 L 3 5 a 2 2 0 0 1 2 -2 Z",
        "M3 9h18",
        "m9 15 2 2 4-4",
    ),
    "library2" to listOf(
        "m16 6 4 14",
        "M12 6v14",
        "M8 8v12",
        "M4 4v16",
    ),
    "target" to listOf(
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0 Z",
        "M 6 12 a 6 6 0 1 0 12 0 a 6 6 0 1 0 -12 0 Z",
        "M 10 12 a 2 2 0 1 0 4 0 a 2 2 0 1 0 -4 0 Z",
    ),
    "practice" to listOf(
        "M 6 2 L 18 2 a 2 2 0 0 1 2 2 L 20 20 a 2 2 0 0 1 -2 2 L 6 22 a 2 2 0 0 1 -2 -2 L 4 4 a 2 2 0 0 1 2 -2 Z",
        "M 8 6 L 16 6",
        "M 16 14 L 16 18",
        "M16 10h.01",
        "M12 10h.01",
        "M8 10h.01",
        "M12 14h.01",
        "M8 14h.01",
        "M12 18h.01",
        "M8 18h.01",
    ),
    "filter" to listOf(
        "M2 5h20",
        "M6 12h12",
        "M9 19h6",
    ),
)

/** The registry from `src/components/ui/icons.tsx`, as vectors. */
object RevisioIcons {
    val dashboard: ImageVector by lazy {
        icon("dashboard", 1.75f, *geometry.getValue("dashboard").toTypedArray())
    }

    val review: ImageVector by lazy {
        icon("review", 1.75f, *geometry.getValue("review").toTypedArray())
    }

    val learn: ImageVector by lazy {
        icon("learn", 1.75f, *geometry.getValue("learn").toTypedArray())
    }

    val cram: ImageVector by lazy {
        icon("cram", 1.75f, *geometry.getValue("cram").toTypedArray())
    }

    val exam: ImageVector by lazy {
        icon("exam", 1.75f, *geometry.getValue("exam").toTypedArray())
    }

    val progress: ImageVector by lazy {
        icon("progress", 1.75f, *geometry.getValue("progress").toTypedArray())
    }

    val library: ImageVector by lazy {
        icon("library", 1.75f, *geometry.getValue("library").toTypedArray())
    }

    val teacher: ImageVector by lazy {
        icon("teacher", 1.75f, *geometry.getValue("teacher").toTypedArray())
    }

    val admin: ImageVector by lazy {
        icon("admin", 1.75f, *geometry.getValue("admin").toTypedArray())
    }

    val due: ImageVector by lazy {
        icon("due", 1.75f, *geometry.getValue("due").toTypedArray())
    }

    val reviewed: ImageVector by lazy {
        icon("reviewed", 1.75f, *geometry.getValue("reviewed").toTypedArray())
    }

    val correct: ImageVector by lazy {
        icon("correct", 1.75f, *geometry.getValue("correct").toTypedArray())
    }

    val streak: ImageVector by lazy {
        icon("streak", 1.75f, *geometry.getValue("streak").toTypedArray())
    }

    val level: ImageVector by lazy {
        icon("level", 1.75f, *geometry.getValue("level").toTypedArray())
    }

    val xp: ImageVector by lazy {
        icon("xp", 1.75f, *geometry.getValue("xp").toTypedArray())
    }

    val league: ImageVector by lazy {
        icon("league", 1.75f, *geometry.getValue("league").toTypedArray())
    }

    val rank: ImageVector by lazy {
        icon("rank", 1.75f, *geometry.getValue("rank").toTypedArray())
    }

    val crown: ImageVector by lazy {
        icon("crown", 1.75f, *geometry.getValue("crown").toTypedArray())
    }

    val clash: ImageVector by lazy {
        icon("clash", 1.75f, *geometry.getValue("clash").toTypedArray())
    }

    val form: ImageVector by lazy {
        icon("form", 1.75f, *geometry.getValue("form").toTypedArray())
    }

    val gauge: ImageVector by lazy {
        icon("gauge", 1.75f, *geometry.getValue("gauge").toTypedArray())
    }

    val zoneUp: ImageVector by lazy {
        icon("zoneUp", 1.75f, *geometry.getValue("zoneUp").toTypedArray())
    }

    val zoneDown: ImageVector by lazy {
        icon("zoneDown", 1.75f, *geometry.getValue("zoneDown").toTypedArray())
    }

    val climb: ImageVector by lazy {
        icon("climb", 1.75f, *geometry.getValue("climb").toTypedArray())
    }

    val next: ImageVector by lazy {
        icon("next", 1.75f, *geometry.getValue("next").toTypedArray())
    }

    val expand: ImageVector by lazy {
        icon("expand", 1.75f, *geometry.getValue("expand").toTypedArray())
    }

    val collapse: ImageVector by lazy {
        icon("collapse", 1.75f, *geometry.getValue("collapse").toTypedArray())
    }

    val search: ImageVector by lazy {
        icon("search", 1.75f, *geometry.getValue("search").toTypedArray())
    }

    val download: ImageVector by lazy {
        icon("download", 1.75f, *geometry.getValue("download").toTypedArray())
    }

    val upload: ImageVector by lazy {
        icon("upload", 1.75f, *geometry.getValue("upload").toTypedArray())
    }

    val rotate: ImageVector by lazy {
        icon("rotate", 1.75f, *geometry.getValue("rotate").toTypedArray())
    }

    val add: ImageVector by lazy {
        icon("add", 1.75f, *geometry.getValue("add").toTypedArray())
    }

    val rocket: ImageVector by lazy {
        icon("rocket", 1.75f, *geometry.getValue("rocket").toTypedArray())
    }

    val edit: ImageVector by lazy {
        icon("edit", 1.75f, *geometry.getValue("edit").toTypedArray())
    }

    val remove: ImageVector by lazy {
        icon("remove", 1.75f, *geometry.getValue("remove").toTypedArray())
    }

    val close: ImageVector by lazy {
        icon("close", 1.75f, *geometry.getValue("close").toTypedArray())
    }

    val signOut: ImageVector by lazy {
        icon("signOut", 1.75f, *geometry.getValue("signOut").toTypedArray())
    }

    val sun: ImageVector by lazy {
        icon("sun", 1.75f, *geometry.getValue("sun").toTypedArray())
    }

    val moon: ImageVector by lazy {
        icon("moon", 1.75f, *geometry.getValue("moon").toTypedArray())
    }

    val more: ImageVector by lazy {
        icon("more", 1.75f, *geometry.getValue("more").toTypedArray())
    }

    val clock: ImageVector by lazy {
        icon("clock", 1.75f, *geometry.getValue("clock").toTypedArray())
    }

    val week: ImageVector by lazy {
        icon("week", 1.75f, *geometry.getValue("week").toTypedArray())
    }

    val resume: ImageVector by lazy {
        icon("resume", 1.75f, *geometry.getValue("resume").toTypedArray())
    }

    val swords: ImageVector by lazy {
        icon("swords", 1.75f, *geometry.getValue("swords").toTypedArray())
    }

    val topic: ImageVector by lazy {
        icon("topic", 1.75f, *geometry.getValue("topic").toTypedArray())
    }

    val notes: ImageVector by lazy {
        icon("notes", 1.75f, *geometry.getValue("notes").toTypedArray())
    }

    val spec: ImageVector by lazy {
        icon("spec", 1.75f, *geometry.getValue("spec").toTypedArray())
    }

    val `class`: ImageVector by lazy {
        icon("class", 1.75f, *geometry.getValue("class").toTypedArray())
    }

    val join: ImageVector by lazy {
        icon("join", 1.75f, *geometry.getValue("join").toTypedArray())
    }

    val publish: ImageVector by lazy {
        icon("publish", 1.75f, *geometry.getValue("publish").toTypedArray())
    }

    val unpublish: ImageVector by lazy {
        icon("unpublish", 1.75f, *geometry.getValue("unpublish").toTypedArray())
    }

    val visible: ImageVector by lazy {
        icon("visible", 1.75f, *geometry.getValue("visible").toTypedArray())
    }

    val merge: ImageVector by lazy {
        icon("merge", 1.75f, *geometry.getValue("merge").toTypedArray())
    }

    val structure: ImageVector by lazy {
        icon("structure", 1.75f, *geometry.getValue("structure").toTypedArray())
    }

    val private: ImageVector by lazy {
        icon("private", 1.75f, *geometry.getValue("private").toTypedArray())
    }

    val person: ImageVector by lazy {
        icon("person", 1.75f, *geometry.getValue("person").toTypedArray())
    }

    val mail: ImageVector by lazy {
        icon("mail", 1.75f, *geometry.getValue("mail").toTypedArray())
    }

    val secure: ImageVector by lazy {
        icon("secure", 1.75f, *geometry.getValue("secure").toTypedArray())
    }

    val achievements: ImageVector by lazy {
        icon("achievements", 1.75f, *geometry.getValue("achievements").toTypedArray())
    }

    val start: ImageVector by lazy {
        icon("start", 1.75f, *geometry.getValue("start").toTypedArray())
    }

    val schedule: ImageVector by lazy {
        icon("schedule", 1.75f, *geometry.getValue("schedule").toTypedArray())
    }

    val checked: ImageVector by lazy {
        icon("checked", 1.75f, *geometry.getValue("checked").toTypedArray())
    }

    val library2: ImageVector by lazy {
        icon("library2", 1.75f, *geometry.getValue("library2").toTypedArray())
    }

    val target: ImageVector by lazy {
        icon("target", 1.75f, *geometry.getValue("target").toTypedArray())
    }

    val practice: ImageVector by lazy {
        icon("practice", 1.75f, *geometry.getValue("practice").toTypedArray())
    }

    val filter: ImageVector by lazy {
        icon("filter", 1.75f, *geometry.getValue("filter").toTypedArray())
    }

    internal val geometry: Map<String, List<String>> by lazy { buildIcons().toMap() }
}

/**
 * The active state of a nav slot, at the weight the web switches to.
 *
 * The bottom bar moves each icon from stroke 1.9 to 2.3 when it becomes the
 * current destination, per the web's BottomNav. Compose bakes a stroke width
 * into the vector, so this is the same geometry built twice rather than a
 * modifier that cannot exist.
 */
object RevisioIconsActive {
    val dashboard: ImageVector by lazy {
        icon("dashboard", 2.3f, *RevisioIcons.geometry.getValue("dashboard").toTypedArray())
    }

    val review: ImageVector by lazy {
        icon("review", 2.3f, *RevisioIcons.geometry.getValue("review").toTypedArray())
    }

    val learn: ImageVector by lazy {
        icon("learn", 2.3f, *RevisioIcons.geometry.getValue("learn").toTypedArray())
    }

    val cram: ImageVector by lazy {
        icon("cram", 2.3f, *RevisioIcons.geometry.getValue("cram").toTypedArray())
    }

    val exam: ImageVector by lazy {
        icon("exam", 2.3f, *RevisioIcons.geometry.getValue("exam").toTypedArray())
    }

    val progress: ImageVector by lazy {
        icon("progress", 2.3f, *RevisioIcons.geometry.getValue("progress").toTypedArray())
    }

    val library: ImageVector by lazy {
        icon("library", 2.3f, *RevisioIcons.geometry.getValue("library").toTypedArray())
    }

    val teacher: ImageVector by lazy {
        icon("teacher", 2.3f, *RevisioIcons.geometry.getValue("teacher").toTypedArray())
    }

    val admin: ImageVector by lazy {
        icon("admin", 2.3f, *RevisioIcons.geometry.getValue("admin").toTypedArray())
    }

    val due: ImageVector by lazy {
        icon("due", 2.3f, *RevisioIcons.geometry.getValue("due").toTypedArray())
    }

    val reviewed: ImageVector by lazy {
        icon("reviewed", 2.3f, *RevisioIcons.geometry.getValue("reviewed").toTypedArray())
    }

    val correct: ImageVector by lazy {
        icon("correct", 2.3f, *RevisioIcons.geometry.getValue("correct").toTypedArray())
    }

    val streak: ImageVector by lazy {
        icon("streak", 2.3f, *RevisioIcons.geometry.getValue("streak").toTypedArray())
    }

    val level: ImageVector by lazy {
        icon("level", 2.3f, *RevisioIcons.geometry.getValue("level").toTypedArray())
    }

    val xp: ImageVector by lazy {
        icon("xp", 2.3f, *RevisioIcons.geometry.getValue("xp").toTypedArray())
    }

    val league: ImageVector by lazy {
        icon("league", 2.3f, *RevisioIcons.geometry.getValue("league").toTypedArray())
    }

    val rank: ImageVector by lazy {
        icon("rank", 2.3f, *RevisioIcons.geometry.getValue("rank").toTypedArray())
    }

    val crown: ImageVector by lazy {
        icon("crown", 2.3f, *RevisioIcons.geometry.getValue("crown").toTypedArray())
    }

    val clash: ImageVector by lazy {
        icon("clash", 2.3f, *RevisioIcons.geometry.getValue("clash").toTypedArray())
    }

    val form: ImageVector by lazy {
        icon("form", 2.3f, *RevisioIcons.geometry.getValue("form").toTypedArray())
    }

    val gauge: ImageVector by lazy {
        icon("gauge", 2.3f, *RevisioIcons.geometry.getValue("gauge").toTypedArray())
    }

    val zoneUp: ImageVector by lazy {
        icon("zoneUp", 2.3f, *RevisioIcons.geometry.getValue("zoneUp").toTypedArray())
    }

    val zoneDown: ImageVector by lazy {
        icon("zoneDown", 2.3f, *RevisioIcons.geometry.getValue("zoneDown").toTypedArray())
    }

    val climb: ImageVector by lazy {
        icon("climb", 2.3f, *RevisioIcons.geometry.getValue("climb").toTypedArray())
    }

    val next: ImageVector by lazy {
        icon("next", 2.3f, *RevisioIcons.geometry.getValue("next").toTypedArray())
    }

    val expand: ImageVector by lazy {
        icon("expand", 2.3f, *RevisioIcons.geometry.getValue("expand").toTypedArray())
    }

    val collapse: ImageVector by lazy {
        icon("collapse", 2.3f, *RevisioIcons.geometry.getValue("collapse").toTypedArray())
    }

    val search: ImageVector by lazy {
        icon("search", 2.3f, *RevisioIcons.geometry.getValue("search").toTypedArray())
    }

    val download: ImageVector by lazy {
        icon("download", 2.3f, *RevisioIcons.geometry.getValue("download").toTypedArray())
    }

    val upload: ImageVector by lazy {
        icon("upload", 2.3f, *RevisioIcons.geometry.getValue("upload").toTypedArray())
    }

    val rotate: ImageVector by lazy {
        icon("rotate", 2.3f, *RevisioIcons.geometry.getValue("rotate").toTypedArray())
    }

    val add: ImageVector by lazy {
        icon("add", 2.3f, *RevisioIcons.geometry.getValue("add").toTypedArray())
    }

    val rocket: ImageVector by lazy {
        icon("rocket", 2.3f, *RevisioIcons.geometry.getValue("rocket").toTypedArray())
    }

    val edit: ImageVector by lazy {
        icon("edit", 2.3f, *RevisioIcons.geometry.getValue("edit").toTypedArray())
    }

    val remove: ImageVector by lazy {
        icon("remove", 2.3f, *RevisioIcons.geometry.getValue("remove").toTypedArray())
    }

    val close: ImageVector by lazy {
        icon("close", 2.3f, *RevisioIcons.geometry.getValue("close").toTypedArray())
    }

    val signOut: ImageVector by lazy {
        icon("signOut", 2.3f, *RevisioIcons.geometry.getValue("signOut").toTypedArray())
    }

    val sun: ImageVector by lazy {
        icon("sun", 2.3f, *RevisioIcons.geometry.getValue("sun").toTypedArray())
    }

    val moon: ImageVector by lazy {
        icon("moon", 2.3f, *RevisioIcons.geometry.getValue("moon").toTypedArray())
    }

    val more: ImageVector by lazy {
        icon("more", 2.3f, *RevisioIcons.geometry.getValue("more").toTypedArray())
    }

    val clock: ImageVector by lazy {
        icon("clock", 2.3f, *RevisioIcons.geometry.getValue("clock").toTypedArray())
    }

    val week: ImageVector by lazy {
        icon("week", 2.3f, *RevisioIcons.geometry.getValue("week").toTypedArray())
    }

    val resume: ImageVector by lazy {
        icon("resume", 2.3f, *RevisioIcons.geometry.getValue("resume").toTypedArray())
    }

    val swords: ImageVector by lazy {
        icon("swords", 2.3f, *RevisioIcons.geometry.getValue("swords").toTypedArray())
    }

    val topic: ImageVector by lazy {
        icon("topic", 2.3f, *RevisioIcons.geometry.getValue("topic").toTypedArray())
    }

    val notes: ImageVector by lazy {
        icon("notes", 2.3f, *RevisioIcons.geometry.getValue("notes").toTypedArray())
    }

    val spec: ImageVector by lazy {
        icon("spec", 2.3f, *RevisioIcons.geometry.getValue("spec").toTypedArray())
    }

    val `class`: ImageVector by lazy {
        icon("class", 2.3f, *RevisioIcons.geometry.getValue("class").toTypedArray())
    }

    val join: ImageVector by lazy {
        icon("join", 2.3f, *RevisioIcons.geometry.getValue("join").toTypedArray())
    }

    val publish: ImageVector by lazy {
        icon("publish", 2.3f, *RevisioIcons.geometry.getValue("publish").toTypedArray())
    }

    val unpublish: ImageVector by lazy {
        icon("unpublish", 2.3f, *RevisioIcons.geometry.getValue("unpublish").toTypedArray())
    }

    val visible: ImageVector by lazy {
        icon("visible", 2.3f, *RevisioIcons.geometry.getValue("visible").toTypedArray())
    }

    val merge: ImageVector by lazy {
        icon("merge", 2.3f, *RevisioIcons.geometry.getValue("merge").toTypedArray())
    }

    val structure: ImageVector by lazy {
        icon("structure", 2.3f, *RevisioIcons.geometry.getValue("structure").toTypedArray())
    }

    val private: ImageVector by lazy {
        icon("private", 2.3f, *RevisioIcons.geometry.getValue("private").toTypedArray())
    }

    val person: ImageVector by lazy {
        icon("person", 2.3f, *RevisioIcons.geometry.getValue("person").toTypedArray())
    }

    val mail: ImageVector by lazy {
        icon("mail", 2.3f, *RevisioIcons.geometry.getValue("mail").toTypedArray())
    }

    val secure: ImageVector by lazy {
        icon("secure", 2.3f, *RevisioIcons.geometry.getValue("secure").toTypedArray())
    }

    val achievements: ImageVector by lazy {
        icon("achievements", 2.3f, *RevisioIcons.geometry.getValue("achievements").toTypedArray())
    }

    val start: ImageVector by lazy {
        icon("start", 2.3f, *RevisioIcons.geometry.getValue("start").toTypedArray())
    }

    val schedule: ImageVector by lazy {
        icon("schedule", 2.3f, *RevisioIcons.geometry.getValue("schedule").toTypedArray())
    }

    val checked: ImageVector by lazy {
        icon("checked", 2.3f, *RevisioIcons.geometry.getValue("checked").toTypedArray())
    }

    val library2: ImageVector by lazy {
        icon("library2", 2.3f, *RevisioIcons.geometry.getValue("library2").toTypedArray())
    }

    val target: ImageVector by lazy {
        icon("target", 2.3f, *RevisioIcons.geometry.getValue("target").toTypedArray())
    }

    val practice: ImageVector by lazy {
        icon("practice", 2.3f, *RevisioIcons.geometry.getValue("practice").toTypedArray())
    }

    val filter: ImageVector by lazy {
        icon("filter", 2.3f, *RevisioIcons.geometry.getValue("filter").toTypedArray())
    }
}
