package app.revisio.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

// GENERATED by scripts/native/make-theme.mjs from src/app/globals.css. Do not edit: re-run
// the script instead.
//
// Two documents own that file, and the reconciliation between them is the
// judgement call it documents: Uber owns the chrome (the ink/canvas duet, the
// grayscale ramp, the pill, the type ladder), Duolingo owns the state (the
// tactile lip under every button, the uppercase tracked label, and colour used
// only where the game needs it — streak, correct, gold). Green is the one
// control that is not navigation: the button you press inside a study session.

/** The palette, in both polarities. Light and dark are the same system flipped. */
data class RevisioColors(
    val background: Color,
    val foreground: Color,
    val card: Color,
    val cardForeground: Color,
    val popover: Color,
    val primary: Color,
    val primaryForeground: Color,
    val secondary: Color,
    val secondaryForeground: Color,
    val muted: Color,
    val mutedForeground: Color,
    val accent: Color,
    val accentForeground: Color,
    val destructive: Color,
    val destructiveForeground: Color,
    val border: Color,
    val borderStrong: Color,
    val input: Color,
    val ring: Color,
    val good: Color,
    val goodPressed: Color,
    val goodSoft: Color,
    val streak: Color,
    val gold: Color,
    val info: Color,
    val band: Color,
    val bandForeground: Color,
    val bandCard: Color,
    val bandBorder: Color,
    val bandMuted: Color,
    val bandSecondary: Color,
    val lip: Color,
    val lipSoft: Color,
    val scrim: Color,
)

private fun hex(value: Long) = Color(value)

val LightColors = RevisioColors(
    background = hex(0xFFFFFFFFL),
    foreground = hex(0xFF000000L),
    card = hex(0xFFFFFFFFL),
    cardForeground = hex(0xFF000000L),
    popover = hex(0xFFFFFFFFL),
    primary = hex(0xFF000000L),
    primaryForeground = hex(0xFFFFFFFFL),
    secondary = hex(0xFFEFEFEFL),
    secondaryForeground = hex(0xFF000000L),
    muted = hex(0xFFF3F3F3L),
    mutedForeground = hex(0xFF5E5E5EL),
    accent = hex(0xFFEFEFEFL),
    accentForeground = hex(0xFF000000L),
    destructive = hex(0xFFFF4B4BL),
    destructiveForeground = hex(0xFFFFFFFFL),
    border = hex(0xFFE2E2E2L),
    borderStrong = hex(0xFFD0D0D0L),
    input = hex(0xFFEFEFEFL),
    ring = hex(0xFF000000L),
    good = hex(0xFF58CC02L),
    goodPressed = hex(0xFF58A700L),
    goodSoft = hex(0xFFD7FFB8L),
    streak = hex(0xFFFF9600L),
    gold = hex(0xFFFFC800L),
    info = hex(0xFF1CB0F6L),
    band = hex(0xFF000000L),
    bandForeground = hex(0xFFFFFFFFL),
    bandCard = hex(0xFF1A1A1AL),
    bandBorder = hex(0xFF333333L),
    bandMuted = hex(0xFFAFAFAFL),
    bandSecondary = hex(0xFF242424L),
    lip = hex(0x47000000L),
    lipSoft = hex(0xFFDCDCDCL),
    scrim = hex(0x66000000L),
)

val DarkColors = RevisioColors(
    background = hex(0xFF000000L),
    foreground = hex(0xFFFFFFFFL),
    card = hex(0xFF141414L),
    cardForeground = hex(0xFFFFFFFFL),
    popover = hex(0xFF1A1A1AL),
    primary = hex(0xFFFFFFFFL),
    primaryForeground = hex(0xFF000000L),
    secondary = hex(0xFF282828L),
    secondaryForeground = hex(0xFFFFFFFFL),
    muted = hex(0xFF1C1C1CL),
    mutedForeground = hex(0xFFAFAFAFL),
    accent = hex(0xFF282828L),
    accentForeground = hex(0xFFFFFFFFL),
    destructive = hex(0xFFFF6B6BL),
    destructiveForeground = hex(0xFF000000L),
    border = hex(0xFF2E2E2EL),
    borderStrong = hex(0xFF4B4B4BL),
    input = hex(0xFF282828L),
    ring = hex(0xFFFFFFFFL),
    good = hex(0xFF58CC02L),
    goodPressed = hex(0xFF3F9400L),
    goodSoft = hex(0xFF1F3608L),
    streak = hex(0xFFFFA53DL),
    gold = hex(0xFFFFD23FL),
    info = hex(0xFF1CB0F6L),
    band = hex(0xFF141414L),
    bandForeground = hex(0xFFFFFFFFL),
    bandCard = hex(0xFF1F1F1FL),
    bandBorder = hex(0xFF2E2E2EL),
    bandMuted = hex(0xFF9A9A9AL),
    bandSecondary = hex(0xFF262626L),
    lip = hex(0xFFC9C9C9L),
    lipSoft = hex(0xFF1F1F1FL),
    scrim = hex(0xA8000000L),
)

/** The radius ladder, and the pill that is the only interactive shape. */
object Radius {
    val xs: Dp = 6.dp
    val sm: Dp = 8.dp
    val md: Dp = 12.dp
    val lg: Dp = 16.dp
    val xl: Dp = 20.dp
    val xxl: Dp = 24.dp
    val pill: Dp = 999.dp
    val base: Dp = 16.dp
}

/** The three documented drops. Cards stay flat: elevation is a colour change. */
object Shadows {

}

data class ShadowSpec(
    val x: Float,
    val y: Float,
    val blur: Float,
    val spread: Float,
    val alpha: Float,
)

/** The two curves the whole app animates on. */
object Easing {
    val snap = CubicBezier(0.16f, 1f, 0.3f, 1f)
    val out = CubicBezier(0.22f, 1f, 0.36f, 1f)
}

data class CubicBezier(val x1: Float, val y1: Float, val x2: Float, val y2: Float)

/**
 * The type ladder. Sizes are the phone step of a responsive scale, which is what
 * the browser shows at the same width.
 */
data class TypeToken(
    val size: Int,
    val weight: FontWeight,
    val lineHeight: Float,
    val tracking: Float,
    val uppercase: Boolean,
)

object Type {
    /** `t-hero` */
    val hero = TypeToken(32, FontWeight(700), 1.08f, 0f, false)
    /** `t-display` */
    val display = TypeToken(28, FontWeight(700), 1.15f, 0f, false)
    /** `t-display-md` */
    val displayMd = TypeToken(24, FontWeight(700), 1.25f, 0f, false)
    /** `t-display-sm` */
    val displaySm = TypeToken(20, FontWeight(700), 1.3f, 0f, false)
    /** `t-title` */
    val title = TypeToken(22, FontWeight(700), 1.25f, 0f, false)
    /** `t-lead` */
    val lead = TypeToken(18, FontWeight(500), 1.4f, 0f, false)
    /** `t-lead-airy` */
    val leadAiry = TypeToken(17, FontWeight(400), 1.45f, 0f, false)
    /** `t-tagline` */
    val tagline = TypeToken(19, FontWeight(700), 1.35f, 0f, false)
    /** `t-strong` */
    val strong = TypeToken(16, FontWeight(500), 1.3f, 0f, false)
    /** `t-body` */
    val body = TypeToken(16, FontWeight(400), 1.5f, 0f, false)
    /** `t-caption` */
    val caption = TypeToken(14, FontWeight(400), 1.43f, 0f, false)
    /** `t-caption-s` */
    val captionS = TypeToken(14, FontWeight(500), 1.3f, 0f, false)
    /** `t-fine` */
    val fine = TypeToken(12, FontWeight(400), 1.35f, 0f, false)
    /** `t-micro` */
    val micro = TypeToken(10, FontWeight(500), 1.3f, 0f, false)
    /** `t-label` */
    val label = TypeToken(14, FontWeight(700), 1.2f, 0.08f, true)
    /** `t-eyebrow` */
    val eyebrow = TypeToken(12, FontWeight(700), 1.3f, 0.1f, true)
    /** `t-num` */
    val num = TypeToken(30, FontWeight(700), 1.1f, 0f, false)
    /** `t-num-sm` */
    val numSm = TypeToken(24, FontWeight(700), 1.15f, 0f, false)
}

/** Geometry the controls are built from, so a tap target is never improvised. */
object Metrics {
    val buttonMinHeight = 44.dp
    val buttonPadding = 20.dp
    val optionMinHeight = 56.dp
    val inputMinHeight = 48.dp
    val inputBorder = 2.dp
    val meterHeight = 10.dp
    val chipMinHeight = 30.dp
    val pillOffset = 3.dp
    val goodLipOffset = 4.dp
    val iconMinHeight = 40.dp
    val navHeight = 64.dp
}
