package app.revisio.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

// GENERATED by scripts/native/make-theme.mjs from src/app/globals.css and src/lib/motion.ts. Do not
// edit: re-run the script instead.
//
// Two documents own that file, and the reconciliation between them is the
// judgement call it documents: Uber owns the chrome (the ink/canvas duet, the
// grayscale ramp, the pill, the type ladder), Duolingo owns the state (the
// tactile lip under every button, the uppercase tracked label, and colour used
// only where the game needs it — streak, correct, gold). Green is the one
// control that is not navigation: the button you press inside a study session.

/** The palette, in both polarities. Light and dark are the same system flipped. */
data class RevisioColors(
    val background: Color,
    val foreground: Color,
    val card: Color,
    val cardForeground: Color,
    val popover: Color,
    val primary: Color,
    val primaryForeground: Color,
    val secondary: Color,
    val secondaryForeground: Color,
    val muted: Color,
    val mutedForeground: Color,
    val accent: Color,
    val accentForeground: Color,
    val destructive: Color,
    val destructiveForeground: Color,
    val border: Color,
    val borderStrong: Color,
    val input: Color,
    val ring: Color,
    val good: Color,
    val goodPressed: Color,
    val goodSoft: Color,
    val streak: Color,
    val gold: Color,
    val info: Color,
    val band: Color,
    val bandForeground: Color,
    val bandCard: Color,
    val bandBorder: Color,
    val bandMuted: Color,
    val bandSecondary: Color,
    val lip: Color,
    val lipSoft: Color,
    val scrim: Color,
)

private fun hex(value: Long) = Color(value)

val LightColors = RevisioColors(
    background = hex(0xFFFFFFFFL),
    foreground = hex(0xFF000000L),
    card = hex(0xFFFFFFFFL),
    cardForeground = hex(0xFF000000L),
    popover = hex(0xFFFFFFFFL),
    primary = hex(0xFF000000L),
    primaryForeground = hex(0xFFFFFFFFL),
    secondary = hex(0xFFEFEFEFL),
    secondaryForeground = hex(0xFF000000L),
    muted = hex(0xFFF3F3F3L),
    mutedForeground = hex(0xFF5E5E5EL),
    accent = hex(0xFFEFEFEFL),
    accentForeground = hex(0xFF000000L),
    destructive = hex(0xFFFF4B4BL),
    destructiveForeground = hex(0xFFFFFFFFL),
    border = hex(0xFFE2E2E2L),
    borderStrong = hex(0xFFD0D0D0L),
    input = hex(0xFFEFEFEFL),
    ring = hex(0xFF000000L),
    good = hex(0xFF58CC02L),
    goodPressed = hex(0xFF58A700L),
    goodSoft = hex(0xFFD7FFB8L),
    streak = hex(0xFFFF9600L),
    gold = hex(0xFFFFC800L),
    info = hex(0xFF1CB0F6L),
    band = hex(0xFF000000L),
    bandForeground = hex(0xFFFFFFFFL),
    bandCard = hex(0xFF1A1A1AL),
    bandBorder = hex(0xFF333333L),
    bandMuted = hex(0xFFAFAFAFL),
    bandSecondary = hex(0xFF242424L),
    lip = hex(0x47000000L),
    lipSoft = hex(0xFFDCDCDCL),
    scrim = hex(0x66000000L),
)

val DarkColors = RevisioColors(
    background = hex(0xFF000000L),
    foreground = hex(0xFFFFFFFFL),
    card = hex(0xFF141414L),
    cardForeground = hex(0xFFFFFFFFL),
    popover = hex(0xFF1A1A1AL),
    primary = hex(0xFFFFFFFFL),
    primaryForeground = hex(0xFF000000L),
    secondary = hex(0xFF282828L),
    secondaryForeground = hex(0xFFFFFFFFL),
    muted = hex(0xFF1C1C1CL),
    mutedForeground = hex(0xFFAFAFAFL),
    accent = hex(0xFF282828L),
    accentForeground = hex(0xFFFFFFFFL),
    destructive = hex(0xFFFF6B6BL),
    destructiveForeground = hex(0xFF000000L),
    border = hex(0xFF2E2E2EL),
    borderStrong = hex(0xFF4B4B4BL),
    input = hex(0xFF282828L),
    ring = hex(0xFFFFFFFFL),
    good = hex(0xFF58CC02L),
    goodPressed = hex(0xFF3F9400L),
    goodSoft = hex(0xFF1F3608L),
    streak = hex(0xFFFFA53DL),
    gold = hex(0xFFFFD23FL),
    info = hex(0xFF1CB0F6L),
    band = hex(0xFF141414L),
    bandForeground = hex(0xFFFFFFFFL),
    bandCard = hex(0xFF1F1F1FL),
    bandBorder = hex(0xFF2E2E2EL),
    bandMuted = hex(0xFF9A9A9AL),
    bandSecondary = hex(0xFF262626L),
    lip = hex(0xFFC9C9C9L),
    lipSoft = hex(0xFF1F1F1FL),
    scrim = hex(0xA8000000L),
)

/** The radius ladder, and the pill that is the only interactive shape. */
object Radius {
    val xs: Dp = 6.dp
    val sm: Dp = 8.dp
    val md: Dp = 12.dp
    val lg: Dp = 16.dp
    val xl: Dp = 20.dp
    val xxl: Dp = 24.dp
    val pill: Dp = 999.dp
    val base: Dp = 16.dp
}

/** The three documented drops. Cards stay flat: elevation is a colour change. */
object Shadows {

}

data class ShadowSpec(
    val x: Float,
    val y: Float,
    val blur: Float,
    val spread: Float,
    val alpha: Float,
)

/** The two curves the whole app animates on. */
object Easing {
    val snap = CubicBezier(0.16f, 1f, 0.3f, 1f)
    val out = CubicBezier(0.22f, 1f, 0.36f, 1f)
}

data class CubicBezier(val x1: Float, val y1: Float, val x2: Float, val y2: Float)

/** The same curve as a Compose `Easing`, for a `tween()`. */
val CubicBezier.easing: androidx.compose.animation.core.Easing
    get() = androidx.compose.animation.core.CubicBezierEasing(x1, y1, x2, y2)

/**
 * A spring, as the web states it, with the conversion Compose needs.
 *
 * Compose's spring has no mass term and describes damping as a ratio of
 * critical, so `mass` is folded into the ratio rather than dropped — the motion
 * that comes out is the browser's, not a stand-in chosen by hand.
 */
data class SpringSpec(val stiffness: Float, val dampingRatio: Float, val mass: Float) {
    /**
     * The animation this spring describes, for any `animate*AsState` call —
     * and for the transitions, which ask for a `FiniteAnimationSpec`.
     */
    fun <T> spec(visibilityThreshold: T? = null): androidx.compose.animation.core.FiniteAnimationSpec<T> =
        androidx.compose.animation.core.spring(
            dampingRatio = dampingRatio,
            stiffness = stiffness,
            visibilityThreshold = visibilityThreshold,
        )
}

/**
 * The motion language — `src/lib/motion.ts`, the single owner of every
 * duration, curve, spring and gesture in the product.
 *
 * The stylesheet carries two curves and nothing else, which is why this port
 * animated on a hand-picked 90ms tween while the browser sprang. Six springs,
 * five durations and the four entrance gestures are read from their owner here
 * instead, so a press or a panel on a phone is the motion the website runs.
 */
object Motion {
    /** Seconds on the web; milliseconds here. */
    object Durations {
        const val instant = 120
        const val quick = 180
        const val base = 300
        const val slow = 460
        const val reveal = 600
    }

    /** The easing curves, as the browser states them. */
    object Curves {
        val out = CubicBezier(0.22f, 1f, 0.36f, 1f)
        val outSoft = CubicBezier(0.21f, 0.47f, 0.32f, 0.98f)
        val inOut = CubicBezier(0.65f, 0f, 0.35f, 1f)
        val easeIn = CubicBezier(0.4f, 0f, 1f, 1f)
    }

    /**
     * The pairs the web actually runs, so no screen has to remember which curve
     * goes with which duration.
     */
    val enter: androidx.compose.animation.core.AnimationSpec<Float> =
        androidx.compose.animation.core.tween(
            durationMillis = Durations.base,
            easing = Curves.out.easing,
        )
    val reveal: androidx.compose.animation.core.AnimationSpec<Float> =
        androidx.compose.animation.core.tween(
            durationMillis = Durations.reveal,
            easing = Curves.out.easing,
        )
    val exit: androidx.compose.animation.core.AnimationSpec<Float> =
        androidx.compose.animation.core.tween(
            durationMillis = Durations.quick,
            easing = Curves.easeIn.easing,
        )

    /** By intent: `settle` is the workhorse, `press` has teeth, `pop` bounces. */
    object Springs {
    /** stiffness 640 · damping 30 · mass 0.5 in the web. */
    val press = SpringSpec(640f, 0.8385f, 0.5f)
    /** stiffness 480 · damping 38 · mass 0.75 in the web. */
    val layout = SpringSpec(480f, 1.0014f, 0.75f)
    /** stiffness 300 · damping 28 · mass 0.85 in the web. */
    val settle = SpringSpec(300f, 0.8767f, 0.85f)
    /** stiffness 150 · damping 26 · mass 1 in the web. */
    val meter = SpringSpec(150f, 1.0614f, 1f)
    /** stiffness 260 · damping 30 · mass 0.9 in the web. */
    val soft = SpringSpec(260f, 0.9806f, 0.9f)
    /** stiffness 420 · damping 22 · mass 0.7 in the web. */
    val pop = SpringSpec(420f, 0.6415f, 0.7f)
    }

    /** Press: the spec's `scale(0.95)`, which every tappable surface uses. */
    const val pressScale = 0.95f
    const val hoverScale = 1.015f

    /** Entrances: rise and settle. Cards arrive at a hair under full size. */
    const val enterRise = 12f
    const val enterScale = 0.96f
    const val enterScaleRise = 8f
    const val routeRise = 10f

    /** A rail that slides in from the side — the ladder advancing a tier. */
    const val railSlide = 32f

    /** A sheet starts this far below the screen, as a fraction of its height. */
    const val sheetTravel = 1.02f

    /** Stagger, and the cap that keeps a long list from trickling in. */
    const val staggerStep = 50
    const val staggerChildren = 40
    const val listStep = 35
    const val listCap = 320

    /** How far above the fold a scroll reveal fires, once. */
    const val revealMargin = 80

    /**
     * The delay before one child of a staggered list arrives.
     *
     * Capped, because `stagger × 200 rows` would leave the last row arriving
     * four seconds after the screen did. The cap is the web's.
     */
    fun stagger(index: Int): Int = minOf(index * listStep, listCap)
}

/**
 * The type ladder. Sizes are the phone step of a responsive scale, which is what
 * the browser shows at the same width.
 */
data class TypeToken(
    val size: Int,
    val weight: FontWeight,
    val lineHeight: Float,
    val tracking: Float,
    val uppercase: Boolean,
)

object Type {
    /** `t-hero` */
    val hero = TypeToken(32, FontWeight(700), 1.08f, 0f, false)
    /** `t-display` */
    val display = TypeToken(28, FontWeight(700), 1.15f, 0f, false)
    /** `t-display-md` */
    val displayMd = TypeToken(24, FontWeight(700), 1.25f, 0f, false)
    /** `t-display-sm` */
    val displaySm = TypeToken(20, FontWeight(700), 1.3f, 0f, false)
    /** `t-title` */
    val title = TypeToken(22, FontWeight(700), 1.25f, 0f, false)
    /** `t-lead` */
    val lead = TypeToken(18, FontWeight(500), 1.4f, 0f, false)
    /** `t-lead-airy` */
    val leadAiry = TypeToken(17, FontWeight(400), 1.45f, 0f, false)
    /** `t-tagline` */
    val tagline = TypeToken(19, FontWeight(700), 1.35f, 0f, false)
    /** `t-strong` */
    val strong = TypeToken(16, FontWeight(500), 1.3f, 0f, false)
    /** `t-body` */
    val body = TypeToken(16, FontWeight(400), 1.5f, 0f, false)
    /** `t-caption` */
    val caption = TypeToken(14, FontWeight(400), 1.43f, 0f, false)
    /** `t-caption-s` */
    val captionS = TypeToken(14, FontWeight(500), 1.3f, 0f, false)
    /** `t-fine` */
    val fine = TypeToken(12, FontWeight(400), 1.35f, 0f, false)
    /** `t-micro` */
    val micro = TypeToken(10, FontWeight(500), 1.3f, 0f, false)
    /** `t-label` */
    val label = TypeToken(14, FontWeight(700), 1.2f, 0.08f, true)
    /** `t-eyebrow` */
    val eyebrow = TypeToken(12, FontWeight(700), 1.3f, 0.1f, true)
    /** `t-num` */
    val num = TypeToken(30, FontWeight(700), 1.1f, 0f, false)
    /** `t-num-sm` */
    val numSm = TypeToken(24, FontWeight(700), 1.15f, 0f, false)
}

/** Geometry the controls are built from, so a tap target is never improvised. */
object Metrics {
    val buttonMinHeight = 44.dp
    val buttonPadding = 20.dp
    val optionMinHeight = 56.dp
    val inputMinHeight = 48.dp
    val inputBorder = 2.dp
    val meterHeight = 10.dp
    val chipMinHeight = 30.dp
    val pillOffset = 3.dp
    val goodLipOffset = 4.dp
    val iconMinHeight = 40.dp
    val navHeight = 64.dp
}
