import Foundation

// GENERATED by scripts/native/make-account.mjs from src/lib/username.ts and src/lib/pronouns.ts.
// Do not edit: re-run the script instead.

/// `USERNAME_RE` — 3–20 chars, starting with a letter or digit.
public let usernamePattern = "^[a-z0-9][a-z0-9_-]{1,19}$"

/// Routes and product words a profile address must never squat on.
public let reservedUsernames: Set<String> = [
    "admin",
    "api",
    "u",
    "me",
    "login",
    "register",
    "logout",
    "settings",
    "dashboard",
    "review",
    "learn",
    "progress",
    "cram",
    "exam",
    "library",
    "teacher",
    "staff",
    "verify-email",
    "profile",
    "account",
    "auth",
    "static",
    "public",
    "about",
    "help",
    "support",
    "revisio",
    "dev",
    "root",
    "sys",
    "system",
    "null",
    "undefined",
]

/// Something close enough to an address to send a confirmation to.
public let emailPattern = "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"

/// Why this handle cannot be used, or nil when it can.
///
/// An empty handle is not a problem — a username is optional, and a learner
/// without one simply has no public address yet.
public func usernameProblem(_ handle: String) -> String? {
    let value = handle.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    if value.isEmpty { return nil }
    guard let regex = try? NSRegularExpression(pattern: usernamePattern, options: [.caseInsensitive]) else {
        return nil
    }
    let range = NSRange(value.startIndex..<value.endIndex, in: value)
    if regex.firstMatch(in: value, options: [], range: range) == nil {
        return "3–20 characters: letters, numbers, hyphens, underscores."
    }
    if reservedUsernames.contains(value) { return "That username is reserved." }
    return nil
}

/// `PRONOUN_MAX` — the cap the server's CHECK enforces.
public let pronounMax = 40

/// The chips Settings offers, in the website's order. A shortcut, never the
/// answer: anything can still be typed.
public let pronounSuggestions: [String] = [
    "she/her",
    "he/him",
    "they/them",
    "she/they",
    "he/they",
    "ask me",
]
