// GENERATED by scripts/native/make-rank.mjs from src/domain/ranked.ts.
// Do not edit: re-run the script instead.
import Foundation

/// The ladder, read out of the web's `domain/ranked.ts`.
///
/// The server decides a learner's rank; this exists because the ladder screen
/// draws all 15 rungs, and the ones nobody has reached are not
/// facts about anybody. Everything here is a constant of the game, so it can be
/// generated once and checked in.
public enum RankLadder {
    /// RP per unit of XP. The two currencies are deliberately the same size.
    public static let rpPerXp = 1

    /// Placements before a rank is awarded.
    public static let placementReviews = 10

    /// Rough XP one review is worth, for "about N reviews" copy.
    public static let reviewsPerRp = 10

    /// A lobby promotes the top share of its seats, floored and capped.
    public static let zoneBandShare = 0.17
    public static let zoneBandMin = 1
    public static let zoneBandMax = 5

    public static let tierOrder = ["bronze", "silver", "gold", "diamond", "legend"]

    public static let divisionSpan: [String: Int] = [
        "bronze": 120,
        "silver": 200,
        "gold": 320,
        "diamond": 500,
        "legend": 750,
    ]

    public static let divisionLabel: [Int: String] = [
        1: "I",
        2: "II",
        3: "III",
    ]

    /// Within a tier we climb III → II → I.
    public static let divisionOrder = [3, 2, 1]

    /// One rung of the ladder, cumulative `base` and all.
    public struct Rung: Equatable, Sendable {
        public let tier: String
        public let division: Int
        public let index: Int
        public let base: Int
        public let span: Int
    }

    public static let rungs: [Rung] = [
        Rung(tier: "bronze", division: 3, index: 0, base: 0, span: 120),
        Rung(tier: "bronze", division: 2, index: 1, base: 120, span: 120),
        Rung(tier: "bronze", division: 1, index: 2, base: 240, span: 120),
        Rung(tier: "silver", division: 3, index: 3, base: 360, span: 200),
        Rung(tier: "silver", division: 2, index: 4, base: 560, span: 200),
        Rung(tier: "silver", division: 1, index: 5, base: 760, span: 200),
        Rung(tier: "gold", division: 3, index: 6, base: 960, span: 320),
        Rung(tier: "gold", division: 2, index: 7, base: 1280, span: 320),
        Rung(tier: "gold", division: 1, index: 8, base: 1600, span: 320),
        Rung(tier: "diamond", division: 3, index: 9, base: 1920, span: 500),
        Rung(tier: "diamond", division: 2, index: 10, base: 2420, span: 500),
        Rung(tier: "diamond", division: 1, index: 11, base: 2920, span: 500),
        Rung(tier: "legend", division: 3, index: 12, base: 3420, span: 750),
        Rung(tier: "legend", division: 2, index: 13, base: 4170, span: 750),
        Rung(tier: "legend", division: 1, index: 14, base: 4920, span: 750),
    ]

    /// Total RP needed to clear the whole ladder.
    public static var topOfLadder: Int { rungs[rungs.count - 1].base }

    public static func tierName(_ tier: String) -> String {
        tier.isEmpty ? tier : tier.prefix(1).uppercased() + tier.dropFirst()
    }

    public static func rpForXp(_ totalXp: Int) -> Int {
        max(0, Int((Double(totalXp) * Double(rpPerXp)).rounded()))
    }

    /// Which rung a quantity of RP sits on. Clamped at both ends.
    public static func rankFor(_ totalXp: Int) -> Rank {
        let points = rpForXp(totalXp)
        var rung = rungs[0]
        for candidate in rungs {
            if points >= candidate.base { rung = candidate } else { break }
        }
        let intoDivision = points - rung.base
        let isApex = rung.index == rungs.count - 1
        let percent = max(0, min(100, Int((Double(intoDivision) / Double(rung.span) * 100).rounded())))
        let label = "\(tierName(rung.tier)) \(divisionLabel[rung.division] ?? "")"
        return Rank(
            tier: rung.tier,
            division: rung.division,
            index: rung.index,
            label: label,
            short: "\(String(tierName(rung.tier).prefix(3)).uppercased()) \(divisionLabel[rung.division] ?? "")",
            points: points,
            intoDivision: intoDivision,
            forDivision: rung.span,
            percent: percent,
            remaining: max(0, rung.span - intoDivision),
            isApex: isApex
        )
    }

    /// Rough reviews needed to earn an amount of RP.
    public static func reviewsForRp(_ rp: Int, perReview: Int = reviewsPerRp) -> Int {
        max(1, Int(ceil(Double(rp) / Double(perReview))))
    }

    /// The promotion and demotion bands inside a weekly lobby.
    public static func zoneBand(_ size: Int) -> Int {
        max(zoneBandMin, min(zoneBandMax, Int((Double(size) * zoneBandShare).rounded())))
    }
}
