// GENERATED by scripts/native/make-rank.mjs from src/domain/srs.ts.
// Do not edit: re-run the script instead.
import Foundation

/// The strength ladder, read out of the web's `domain/srs.ts`.
///
/// The server grades every card onto one of these twelve rungs; this exists
/// because the staff progress sheet draws all 12 of them — including the
/// ones this learner holds no cards on — and a rail of rungs is a constant of
/// the game, not a fact about anybody.
public enum SrsLadder {
    /// One rung. `interval` is what a review at this level earns; nil at the summit.
    public struct Rung: Equatable, Sendable {
        public let level: Int
        public let tier: String
        public let label: String
        public let interval: String?
    }

    public static let rungs: [Rung] = [
        Rung(level: 1, tier: "beginner", label: "Beginner I", interval: "4h"),
        Rung(level: 2, tier: "beginner", label: "Beginner II", interval: "8h"),
        Rung(level: 3, tier: "beginner", label: "Beginner III", interval: "1d"),
        Rung(level: 4, tier: "adept", label: "Adept I", interval: "2d"),
        Rung(level: 5, tier: "adept", label: "Adept II", interval: "4d"),
        Rung(level: 6, tier: "adept", label: "Adept III", interval: "8d"),
        Rung(level: 7, tier: "seasoned", label: "Seasoned I", interval: "2w"),
        Rung(level: 8, tier: "seasoned", label: "Seasoned II", interval: "1mo"),
        Rung(level: 9, tier: "seasoned", label: "Seasoned III", interval: "2mo"),
        Rung(level: 10, tier: "mastered", label: "Mastered I", interval: "4mo"),
        Rung(level: 11, tier: "mastered", label: "Mastered II", interval: "6mo"),
        Rung(level: 12, tier: "mastered", label: "Mastered", interval: nil),
    ]

    /// The rung's display name, clamped — the level 12 label carries no numeral.
    public static func labelFor(_ level: Int) -> String {
        rungs[max(0, min(rungs.count - 1, level - 1))].label
    }

    /// The rung's compact interval chip ("4h", "2w"), or nil at the summit.
    public static func intervalFor(_ level: Int) -> String? {
        rungs[max(0, min(rungs.count - 1, level - 1))].interval
    }
}
