package app.revisio.engine

// GENERATED by scripts/native/make-account.mjs from src/lib/username.ts and src/lib/pronouns.ts.
// Do not edit: re-run the script instead.

/** `USERNAME_RE` — 3–20 chars, starting with a letter or digit. */
val USERNAME_RE = Regex("^[a-z0-9][a-z0-9_-]{1,19}$", RegexOption.IGNORE_CASE)

/** Routes and product words a profile address must never squat on. */
val RESERVED_USERNAMES: Set<String> = setOf(
    "admin",
    "api",
    "u",
    "me",
    "login",
    "register",
    "logout",
    "settings",
    "dashboard",
    "review",
    "learn",
    "progress",
    "cram",
    "exam",
    "library",
    "teacher",
    "staff",
    "verify-email",
    "profile",
    "account",
    "auth",
    "static",
    "public",
    "about",
    "help",
    "support",
    "revisio",
    "dev",
    "root",
    "sys",
    "system",
    "null",
    "undefined",
)

/**
 * Something close enough to an address to send a confirmation to. The server is
 * the real judge; this only keeps a clearly malformed string from making a round
 * trip that was going to be refused.
 */
val EMAIL_RE = Regex("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")

/**
 * Why this handle cannot be used, or null when it can.
 *
 * An empty handle is not a problem — a username is optional, and a learner
 * without one simply has no public address yet.
 */
fun usernameProblem(handle: String): String? {
    val value = handle.trim().lowercase()
    if (value.isEmpty()) return null
    if (!USERNAME_RE.matches(value)) return "3–20 characters: letters, numbers, hyphens, underscores."
    if (value in RESERVED_USERNAMES) return "That username is reserved."
    return null
}

/** `PRONOUN_MAX` — the cap the server's CHECK enforces. */
val PRONOUN_MAX: Int = 40

/**
 * The chips Settings offers, in the website's order. A shortcut, never the
 * answer: anything can still be typed.
 */
val PRONOUN_SUGGESTIONS: List<String> = listOf(
    "she/her",
    "he/him",
    "they/them",
    "she/they",
    "he/they",
    "ask me",
)
