// GENERATED by scripts/native/make-rank.mjs from src/domain/ranked.ts.
// Do not edit: re-run the script instead.
package app.revisio.engine

import kotlin.math.ceil
import kotlin.math.roundToInt

/**
 * The ladder, read out of the web's `domain/ranked.ts`.
 *
 * The server decides a learner's rank; this exists because the ladder screen
 * draws all 15 rungs, and the ones nobody has reached are not
 * facts about anybody. Everything here is a constant of the game, so it can be
 * generated once and checked in.
 */
object RankLadder {
    /** RP per unit of XP. The two currencies are deliberately the same size. */
    const val RP_PER_XP = 1

    /** Placements before a rank is awarded. */
    const val PLACEMENT_REVIEWS = 10

    /** Rough XP one review is worth, for "about N reviews" copy. */
    const val REVIEWS_PER_RP = 10

    /** A lobby promotes the top share of its seats, floored and capped. */
    const val ZONE_BAND_SHARE = 0.17
    const val ZONE_BAND_MIN = 1
    const val ZONE_BAND_MAX = 5

    val TIER_ORDER: List<String> = listOf("bronze", "silver", "gold", "diamond", "legend")

    val DIVISION_SPAN: Map<String, Int> = mapOf(
        "bronze" to 120,
        "silver" to 200,
        "gold" to 320,
        "diamond" to 500,
        "legend" to 750,
    )

    val DIVISION_LABEL: Map<Int, String> = mapOf(
        1 to "I",
        2 to "II",
        3 to "III",
    )

    /** Within a tier we climb III → II → I. */
    val DIVISION_ORDER: List<Int> = listOf(3, 2, 1)

    /** One rung of the ladder, cumulative `base` and all. */
    data class Rung(
        val tier: String,
        val division: Int,
        val index: Int,
        val base: Int,
        val span: Int,
    )

    val rungs: List<Rung> = listOf(
    Rung("bronze", 3, 0, 0, 120),
    Rung("bronze", 2, 1, 120, 120),
    Rung("bronze", 1, 2, 240, 120),
    Rung("silver", 3, 3, 360, 200),
    Rung("silver", 2, 4, 560, 200),
    Rung("silver", 1, 5, 760, 200),
    Rung("gold", 3, 6, 960, 320),
    Rung("gold", 2, 7, 1280, 320),
    Rung("gold", 1, 8, 1600, 320),
    Rung("diamond", 3, 9, 1920, 500),
    Rung("diamond", 2, 10, 2420, 500),
    Rung("diamond", 1, 11, 2920, 500),
    Rung("legend", 3, 12, 3420, 750),
    Rung("legend", 2, 13, 4170, 750),
    Rung("legend", 1, 14, 4920, 750),
    )

    /** Total RP needed to clear the whole ladder. */
    val TOP_OF_LADDER: Int = rungs.last().base

    fun tierName(tier: String): String =
        tier.replaceFirstChar { it.uppercaseChar() }

    fun rpForXp(totalXp: Int): Int = maxOf(0, (totalXp.toDouble() * RP_PER_XP).roundToInt())

    /** Which rung a quantity of RP sits on. Clamped at both ends. */
    fun rankFor(totalXp: Int): Rank {
        val points = rpForXp(totalXp)
        var rung = rungs.first()
        for (candidate in rungs) {
            if (points >= candidate.base) rung = candidate else break
        }
        val intoDivision = points - rung.base
        val isApex = rung.index == rungs.size - 1
        val percent = ((intoDivision.toDouble() / rung.span) * 100).roundToInt().coerceIn(0, 100)
        val label = "${tierName(rung.tier)} ${DIVISION_LABEL[rung.division]}"
        return Rank(
            tier = rung.tier,
            division = rung.division,
            index = rung.index,
            label = label,
            short = "${tierName(rung.tier).take(3).uppercase()} ${DIVISION_LABEL[rung.division]}",
            points = points,
            intoDivision = intoDivision,
            forDivision = rung.span,
            percent = percent,
            remaining = maxOf(0, rung.span - intoDivision),
            isApex = isApex,
        )
    }

    /** Rough reviews needed to earn an amount of RP. */
    fun reviewsForRp(rp: Int, perReview: Int = REVIEWS_PER_RP): Int =
        maxOf(1, ceil(rp.toDouble() / perReview).toInt())

    /**
     * The promotion and demotion bands inside a weekly lobby.
     *
     * Proportional, with a floor of one and a ceiling of five: a lobby of four
     * people should not promote three of them.
     */
    fun zoneBand(size: Int): Int =
        (size * ZONE_BAND_SHARE).roundToInt().coerceIn(ZONE_BAND_MIN, ZONE_BAND_MAX)
}
