// GENERATED by scripts/native/make-rank.mjs from src/domain/srs.ts.
// Do not edit: re-run the script instead.
package app.revisio.engine

/**
 * The strength ladder, read out of the web's `domain/srs.ts`.
 *
 * The server grades every card onto one of these twelve rungs; this exists
 * because the staff progress sheet draws all 12 of them — including the
 * ones this learner holds no cards on — and a rail of rungs is a constant of
 * the game, not a fact about anybody.
 */
object SrsLadder {
    /** One rung. `interval` is what a review at this level earns; null at the summit. */
    data class Rung(
        val level: Int,
        val tier: String,
        val label: String,
        val interval: String?,
    )

    val rungs: List<Rung> = listOf(
        Rung(1, "beginner", "Beginner I", "4h"),
        Rung(2, "beginner", "Beginner II", "8h"),
        Rung(3, "beginner", "Beginner III", "1d"),
        Rung(4, "adept", "Adept I", "2d"),
        Rung(5, "adept", "Adept II", "4d"),
        Rung(6, "adept", "Adept III", "8d"),
        Rung(7, "seasoned", "Seasoned I", "2w"),
        Rung(8, "seasoned", "Seasoned II", "1mo"),
        Rung(9, "seasoned", "Seasoned III", "2mo"),
        Rung(10, "mastered", "Mastered I", "4mo"),
        Rung(11, "mastered", "Mastered II", "6mo"),
        Rung(12, "mastered", "Mastered", null),
    )

    /** The rung's display name, clamped — the level 12 label carries no numeral. */
    fun labelFor(level: Int): String = rungs[(level - 1).coerceIn(rungs.indices)].label

    /** The rung's compact interval chip ("4h", "2w"), or null at the summit. */
    fun intervalFor(level: Int): String? = rungs[(level - 1).coerceIn(rungs.indices)].interval
}
