#!/usr/bin/env node
// GENERATED CLIENT RULES — the account form's rules, emitted for both phones.
//
// `src/lib/username.ts` is the single owner of what a username may be: the
// server-side profile module imports it, and the web settings form uses it to
// disable its own Save button. The native clients have to give the same feedback
// before the request is made, or a learner types a handle the server will reject
// and finds out from an error toast instead of from the field.
//
// So this reads the web module and emits the same two facts — the pattern and
// the reserved set — into Kotlin and Swift. Copying the list by hand would rot
// the first time a route is added; a generated file cannot disagree.
//
// `src/lib/pronouns.ts` gets the same treatment for the same reason: the
// settings form offers a shortlist of chips, and a phone that offered a
// different shortlist would be telling someone their pronouns were not one of
// the options. The cap travels with it for the same reason the pattern does —
// so the field can grey out Save before the round trip.
//
//   node scripts/native/make-account.mjs
//
// Run it whenever `src/lib/username.ts` or `src/lib/pronouns.ts` changes.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const source = join(root, 'src', 'lib', 'username.ts');
const ts = readFileSync(source, 'utf8');

const pattern = /\bUSERNAME_RE\s*=\s*\/(.+?)\/([a-z]*)/.exec(ts);
if (!pattern) throw new Error(`could not read USERNAME_RE from ${source}`);
const [, source_, flags] = pattern;

const reservedBlock = /RESERVED_USERNAMES\s*=\s*new Set\(\[([\s\S]*?)\]\)/.exec(ts);
if (!reservedBlock) throw new Error(`could not read RESERVED_USERNAMES from ${source}`);
const reserved = [...reservedBlock[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
if (reserved.length === 0) throw new Error('RESERVED_USERNAMES parsed empty — refusing to write a list that allows every word');

// The source is a JS regex; the clients need the same shape in their own
// dialect. Anchors, classes and braces carry over unchanged — but a JS-only
// construct must fail here rather than silently become a different rule.
if (!/^\^.*\$$/.test(source_)) throw new Error(`USERNAME_RE is not anchored: ${source_}`);
if (/\(\?!|\(\?<|\\p\{/.test(source_)) throw new Error('USERNAME_RE uses a construct that does not port to Kotlin/Swift regex as written');

const HEADER = [
  'GENERATED by scripts/native/make-account.mjs from src/lib/username.ts and src/lib/pronouns.ts.',
  'Do not edit: re-run the script instead.',
];

// ── pronouns ─────────────────────────────────────────────────────────────────
// The shortlist and the cap are read out of the web module rather than written
// here, so adding a chip to the website adds it to both phones in the same
// commit that changed the website.

const pronounsSource = join(root, 'src', 'lib', 'pronouns.ts');
const pronounsTs = readFileSync(pronounsSource, 'utf8');

const maxMatch = /\bPRONOUN_MAX\s*=\s*(\d+)/.exec(pronounsTs);
if (!maxMatch) throw new Error(`could not read PRONOUN_MAX from ${pronounsSource}`);
const pronounMax = Number(maxMatch[1]);

const suggestionBlock = /\bPRONOUN_SUGGESTIONS\s*=\s*\[([\s\S]*?)\]\s*as const/.exec(pronounsTs);
if (!suggestionBlock) throw new Error(`could not read PRONOUN_SUGGESTIONS from ${pronounsSource}`);
const suggestions = [...suggestionBlock[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
if (suggestions.length === 0) {
  throw new Error('PRONOUN_SUGGESTIONS parsed empty — refusing to write a settings form with no chips');
}
if (suggestions.some((s) => /['\\]/.test(s))) {
  throw new Error('PRONOUN_SUGGESTIONS holds a quote or backslash, which would not survive emission verbatim');
}

// ── Kotlin ──────────────────────────────────────────────────────────────────

const kotlinPath = join(root, 'mobile', 'android', 'engine', 'src', 'main', 'kotlin', 'app', 'revisio', 'engine', 'AccountRules.kt');
const kotlin = `package app.revisio.engine

${HEADER.map((line) => `// ${line}`).join('\n')}

/** \`USERNAME_RE\` — 3–20 chars, starting with a letter or digit. */
val USERNAME_RE = Regex("${source_}", RegexOption.IGNORE_CASE)

/** Routes and product words a profile address must never squat on. */
val RESERVED_USERNAMES: Set<String> = setOf(
${reserved.map((word) => `    "${word}",`).join('\n')}
)

/**
 * Something close enough to an address to send a confirmation to. The server is
 * the real judge; this only keeps a clearly malformed string from making a round
 * trip that was going to be refused.
 */
val EMAIL_RE = Regex("^[^\\\\s@]+@[^\\\\s@]+\\\\.[^\\\\s@]+$")

/**
 * Why this handle cannot be used, or null when it can.
 *
 * An empty handle is not a problem — a username is optional, and a learner
 * without one simply has no public address yet.
 */
fun usernameProblem(handle: String): String? {
    val value = handle.trim().lowercase()
    if (value.isEmpty()) return null
    if (!USERNAME_RE.matches(value)) return "3–20 characters: letters, numbers, hyphens, underscores."
    if (value in RESERVED_USERNAMES) return "That username is reserved."
    return null
}

/** \`PRONOUN_MAX\` — the cap the server's CHECK enforces. */
val PRONOUN_MAX: Int = ${pronounMax}

/**
 * The chips Settings offers, in the website's order. A shortcut, never the
 * answer: anything can still be typed.
 */
val PRONOUN_SUGGESTIONS: List<String> = listOf(
${suggestions.map((word) => `    "${word}",`).join('\n')}
)
`;

// ── Swift ───────────────────────────────────────────────────────────────────

const swiftPath = join(root, 'mobile', 'ios', 'Sources', 'RevisioEngine', 'AccountRules.swift');
const swift = `import Foundation

${HEADER.map((line) => `// ${line}`).join('\n')}

/// \`USERNAME_RE\` — 3–20 chars, starting with a letter or digit.
public let usernamePattern = "${source_}"

/// Routes and product words a profile address must never squat on.
public let reservedUsernames: Set<String> = [
${reserved.map((word) => `    "${word}",`).join('\n')}
]

/// Something close enough to an address to send a confirmation to.
public let emailPattern = "^[^\\\\s@]+@[^\\\\s@]+\\\\.[^\\\\s@]+$"

/// Why this handle cannot be used, or nil when it can.
///
/// An empty handle is not a problem — a username is optional, and a learner
/// without one simply has no public address yet.
public func usernameProblem(_ handle: String) -> String? {
    let value = handle.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    if value.isEmpty { return nil }
    guard let regex = try? NSRegularExpression(pattern: usernamePattern, options: [.caseInsensitive]) else {
        return nil
    }
    let range = NSRange(value.startIndex..<value.endIndex, in: value)
    if regex.firstMatch(in: value, options: [], range: range) == nil {
        return "3–20 characters: letters, numbers, hyphens, underscores."
    }
    if reservedUsernames.contains(value) { return "That username is reserved." }
    return nil
}

/// \`PRONOUN_MAX\` — the cap the server's CHECK enforces.
public let pronounMax = ${pronounMax}

/// The chips Settings offers, in the website's order. A shortcut, never the
/// answer: anything can still be typed.
public let pronounSuggestions: [String] = [
${suggestions.map((word) => `    "${word}",`).join('\n')}
]
`;

for (const [path, body] of [[kotlinPath, kotlin], [swiftPath, swift]]) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body);
  console.log(`account: wrote ${relative(root, path)}`);
}
console.log(`account: /${source_}/${flags} · ${reserved.length} reserved names · ${suggestions.length} pronoun chips`);
