#!/usr/bin/env node
// ── The rank ladder, generated from the web's own rule ──────────────────────
//
// `src/domain/ranked.ts` is the one owner of what a rank *is*: fifteen rungs,
// five tiers of three divisions, widening bands, RP measured in XP. The server
// computes a learner's rank from it and the browser draws the ladder from it.
//
// The phones need the same numbers for one reason the payload cannot cover: the
// ladder view draws **every** rung, including the twelve the learner has not
// reached, and a rail of rungs cannot be sent as a fact about one learner. So
// the constants are read out of that module here and emitted into both engines,
// rather than transcribed by hand where they would drift on the next balance
// change.
//
// What is generated: the ladder itself, the tier order and spans, the division
// labels, and the three numeric rules that read them (`rankFor`, `reviewsForRp`,
// `zoneBand`). What is *not* generated: the sentences the screens say. Those live
// in the screens, next to the layout they belong to.
//
// Run: node scripts/native/make-rank.mjs   (or `npm run native:generate`)

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const source = readFileSync(resolve(root, 'src/domain/ranked.ts'), 'utf8');

/** Read `export const NAME = <literal>` out of the module. */
function constSource(name) {
  const match = source.match(new RegExp(`export const ${name}\\s*(?::[^=]+)?=\\s*([\\s\\S]*?);\\n`));
  if (!match) throw new Error(`make-rank: could not find ${name} in src/domain/ranked.ts`);
  return match[1];
}

const spanSource = constSource('DIVISION_SPAN');
const tierSource = constSource('TIER_ORDER');
const labelSource = constSource('DIVISION_LABEL');
const rpPerXp = Number(constSource('RP_PER_XP'));
const placementReviews = Number(constSource('PLACEMENT_REVIEWS'));

const TIER_ORDER = [...tierSource.matchAll(/'([a-z]+)'|"([a-z]+)"/g)].map((m) => m[1] ?? m[2]);
const DIVISION_SPAN = Object.fromEntries(
  [...spanSource.matchAll(/([a-z]+)\s*:\s*(\d+)/g)].map((m) => [m[1], Number(m[2])]),
);
const DIVISION_LABEL = Object.fromEntries(
  [...labelSource.matchAll(/(\d)\s*:\s*'([^']+)'/g)].map((m) => [Number(m[1]), m[2]]),
);
// Within a tier we climb III → II → I, the way competitive ladders read.
const DIVISION_ORDER = [3, 2, 1];

if (!TIER_ORDER.length || !Object.keys(DIVISION_SPAN).length) {
  throw new Error('make-rank: the ladder constants did not parse');
}
for (const tier of TIER_ORDER) {
  if (!(tier in DIVISION_SPAN)) throw new Error(`make-rank: no span for tier ${tier}`);
}

/** The fifteen rungs, `base` being the cumulative RP to *enter* the rank. */
const rungs = [];
{
  let base = 0;
  let index = 0;
  for (const tier of TIER_ORDER) {
    for (const division of DIVISION_ORDER) {
      rungs.push({ tier, division, index, base, span: DIVISION_SPAN[tier] });
      base += DIVISION_SPAN[tier];
      index += 1;
    }
  }
}

const sortedDivisions = [...DIVISION_ORDER].sort((a, b) => a - b);

// ── Kotlin ──────────────────────────────────────────────────────────────────

const kotlinRungs = rungs
  .map(
    (r) =>
      `    Rung("${r.tier}", ${r.division}, ${r.index}, ${r.base}, ${r.span}),`,
  )
  .join('\n');

const kotlin = `// GENERATED by scripts/native/make-rank.mjs from src/domain/ranked.ts.
// Do not edit: re-run the script instead.
package app.revisio.engine

import kotlin.math.ceil
import kotlin.math.roundToInt

/**
 * The ladder, read out of the web's \`domain/ranked.ts\`.
 *
 * The server decides a learner's rank; this exists because the ladder screen
 * draws all ${rungs.length} rungs, and the ones nobody has reached are not
 * facts about anybody. Everything here is a constant of the game, so it can be
 * generated once and checked in.
 */
object RankLadder {
    /** RP per unit of XP. The two currencies are deliberately the same size. */
    const val RP_PER_XP = ${rpPerXp}

    /** Placements before a rank is awarded. */
    const val PLACEMENT_REVIEWS = ${placementReviews}

    /** Rough XP one review is worth, for "about N reviews" copy. */
    const val REVIEWS_PER_RP = 10

    /** A lobby promotes the top share of its seats, floored and capped. */
    const val ZONE_BAND_SHARE = 0.17
    const val ZONE_BAND_MIN = 1
    const val ZONE_BAND_MAX = 5

    val TIER_ORDER: List<String> = listOf(${TIER_ORDER.map((t) => `"${t}"`).join(', ')})

    val DIVISION_SPAN: Map<String, Int> = mapOf(
${TIER_ORDER.map((t) => `        "${t}" to ${DIVISION_SPAN[t]},`).join('\n')}
    )

    val DIVISION_LABEL: Map<Int, String> = mapOf(
${sortedDivisions.map((d) => `        ${d} to "${DIVISION_LABEL[d]}",`).join('\n')}
    )

    /** Within a tier we climb III → II → I. */
    val DIVISION_ORDER: List<Int> = listOf(${DIVISION_ORDER.join(', ')})

    /** One rung of the ladder, cumulative \`base\` and all. */
    data class Rung(
        val tier: String,
        val division: Int,
        val index: Int,
        val base: Int,
        val span: Int,
    )

    val rungs: List<Rung> = listOf(
${kotlinRungs}
    )

    /** Total RP needed to clear the whole ladder. */
    val TOP_OF_LADDER: Int = rungs.last().base

    fun tierName(tier: String): String =
        tier.replaceFirstChar { it.uppercaseChar() }

    fun rpForXp(totalXp: Int): Int = maxOf(0, (totalXp.toDouble() * RP_PER_XP).roundToInt())

    /** Which rung a quantity of RP sits on. Clamped at both ends. */
    fun rankFor(totalXp: Int): Rank {
        val points = rpForXp(totalXp)
        var rung = rungs.first()
        for (candidate in rungs) {
            if (points >= candidate.base) rung = candidate else break
        }
        val intoDivision = points - rung.base
        val isApex = rung.index == rungs.size - 1
        val percent = ((intoDivision.toDouble() / rung.span) * 100).roundToInt().coerceIn(0, 100)
        val label = "\${tierName(rung.tier)} \${DIVISION_LABEL[rung.division]}"
        return Rank(
            tier = rung.tier,
            division = rung.division,
            index = rung.index,
            label = label,
            short = "\${tierName(rung.tier).take(3).uppercase()} \${DIVISION_LABEL[rung.division]}",
            points = points,
            intoDivision = intoDivision,
            forDivision = rung.span,
            percent = percent,
            remaining = maxOf(0, rung.span - intoDivision),
            isApex = isApex,
        )
    }

    /** Rough reviews needed to earn an amount of RP. */
    fun reviewsForRp(rp: Int, perReview: Int = REVIEWS_PER_RP): Int =
        maxOf(1, ceil(rp.toDouble() / perReview).toInt())

    /**
     * The promotion and demotion bands inside a weekly lobby.
     *
     * Proportional, with a floor of one and a ceiling of five: a lobby of four
     * people should not promote three of them.
     */
    fun zoneBand(size: Int): Int =
        (size * ZONE_BAND_SHARE).roundToInt().coerceIn(ZONE_BAND_MIN, ZONE_BAND_MAX)
}
`;

// ── Swift ───────────────────────────────────────────────────────────────────

const swiftRungs = rungs
  .map((r) => `        Rung(tier: "${r.tier}", division: ${r.division}, index: ${r.index}, base: ${r.base}, span: ${r.span}),`)
  .join('\n');

const swift = `// GENERATED by scripts/native/make-rank.mjs from src/domain/ranked.ts.
// Do not edit: re-run the script instead.
import Foundation

/// The ladder, read out of the web's \`domain/ranked.ts\`.
///
/// The server decides a learner's rank; this exists because the ladder screen
/// draws all ${rungs.length} rungs, and the ones nobody has reached are not
/// facts about anybody. Everything here is a constant of the game, so it can be
/// generated once and checked in.
public enum RankLadder {
    /// RP per unit of XP. The two currencies are deliberately the same size.
    public static let rpPerXp = ${rpPerXp}

    /// Placements before a rank is awarded.
    public static let placementReviews = ${placementReviews}

    /// Rough XP one review is worth, for "about N reviews" copy.
    public static let reviewsPerRp = 10

    /// A lobby promotes the top share of its seats, floored and capped.
    public static let zoneBandShare = 0.17
    public static let zoneBandMin = 1
    public static let zoneBandMax = 5

    public static let tierOrder = [${TIER_ORDER.map((t) => `"${t}"`).join(', ')}]

    public static let divisionSpan: [String: Int] = [
${TIER_ORDER.map((t) => `        "${t}": ${DIVISION_SPAN[t]},`).join('\n')}
    ]

    public static let divisionLabel: [Int: String] = [
${sortedDivisions.map((d) => `        ${d}: "${DIVISION_LABEL[d]}",`).join('\n')}
    ]

    /// Within a tier we climb III → II → I.
    public static let divisionOrder = [${DIVISION_ORDER.join(', ')}]

    /// One rung of the ladder, cumulative \`base\` and all.
    public struct Rung: Equatable, Sendable {
        public let tier: String
        public let division: Int
        public let index: Int
        public let base: Int
        public let span: Int
    }

    public static let rungs: [Rung] = [
${swiftRungs}
    ]

    /// Total RP needed to clear the whole ladder.
    public static var topOfLadder: Int { rungs[rungs.count - 1].base }

    public static func tierName(_ tier: String) -> String {
        tier.isEmpty ? tier : tier.prefix(1).uppercased() + tier.dropFirst()
    }

    public static func rpForXp(_ totalXp: Int) -> Int {
        max(0, Int((Double(totalXp) * Double(rpPerXp)).rounded()))
    }

    /// Which rung a quantity of RP sits on. Clamped at both ends.
    public static func rankFor(_ totalXp: Int) -> Rank {
        let points = rpForXp(totalXp)
        var rung = rungs[0]
        for candidate in rungs {
            if points >= candidate.base { rung = candidate } else { break }
        }
        let intoDivision = points - rung.base
        let isApex = rung.index == rungs.count - 1
        let percent = max(0, min(100, Int((Double(intoDivision) / Double(rung.span) * 100).rounded())))
        let label = "\\(tierName(rung.tier)) \\(divisionLabel[rung.division] ?? "")"
        return Rank(
            tier: rung.tier,
            division: rung.division,
            index: rung.index,
            label: label,
            short: "\\(String(tierName(rung.tier).prefix(3)).uppercased()) \\(divisionLabel[rung.division] ?? "")",
            points: points,
            intoDivision: intoDivision,
            forDivision: rung.span,
            percent: percent,
            remaining: max(0, rung.span - intoDivision),
            isApex: isApex
        )
    }

    /// Rough reviews needed to earn an amount of RP.
    public static func reviewsForRp(_ rp: Int, perReview: Int = reviewsPerRp) -> Int {
        max(1, Int(ceil(Double(rp) / Double(perReview))))
    }

    /// The promotion and demotion bands inside a weekly lobby.
    public static func zoneBand(_ size: Int) -> Int {
        max(zoneBandMin, min(zoneBandMax, Int((Double(size) * zoneBandShare).rounded())))
    }
}
`;

const targets = [
  ['mobile/android/engine/src/main/kotlin/app/revisio/engine/RankLadder.kt', kotlin],
  ['mobile/ios/Sources/RevisioEngine/RankLadder.swift', swift],
];

for (const [path, contents] of targets) {
  const full = resolve(root, path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, contents);
}

// A sanity check the generators can run instead of a test: the ladder must be a
// contiguous climb, or the rail would draw a gap nobody can cross.
for (let i = 1; i < rungs.length; i += 1) {
  const previous = rungs[i - 1];
  if (rungs[i].base !== previous.base + previous.span) {
    throw new Error(`make-rank: rung ${i} does not start where rung ${i - 1} ends`);
  }
}

console.log(
  `rank: ${rungs.length} rungs, ${TIER_ORDER.length} tiers, top of ladder ${rungs[rungs.length - 1].base} RP → RankLadder.kt, RankLadder.swift`,
);
